### ISSUE TITLE
EPIC: Accessibility Testing - Dev Team 

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#1060]
### Dependency
- [x] https://github.com/hackforla/expunge-assist/issues/959

Overview
The research team has conducted initial accessibility audit and assessment of EA landing page and letter generator. 

### Action Items
- [x] Review UXR insights [Link](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?type=whiteboard&node-id=1670-2433&t=Yi1VsGXwBweTumLp-0)
- [x] dev-specific accessibility testing [Link](https://docs.google.com/document/d/1uLyhHuX53qoyPdyb1aU6tg1V7nKpPGjka8JTT72pK58/edit?usp=sharing)
- [x] develop issues from the UXR insights
- [x] #1074 
- [x] #1229
- [x] #1230
- [x] #1232
- [x] #1233
- [x] #1236
- [x] #1237
- [x] #1238
