### ISSUE TITLE
Design 404 page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1137]
### Dependency 
- [x] #1171 

### Overview
Our 404 page doesn't match our current design styles. 

### Action Items
- [x] update design 
- [x] notify content team that #1171 is ready to be worked on
- [x] add design to #1138
- [x] remove `dependency` label from #1138 and add `ready for dev lead` label

### Resources/Notes
![screenshot of 404 page](https://private-user-images.githubusercontent.com/75542938/301992562-c57baf6f-db52-44ca-af4f-292b824b8e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MTYwMzAsIm5iZiI6MTcwNjkxNTczMCwicGF0aCI6Ii83NTU0MjkzOC8zMDE5OTI1NjItYzU3YmFmNmYtZGI1Mi00NGNhLWFmNGYtMjkyYjgyNGI4ZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDIzMTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNDA1NjZhOWIzZDQ4ZDE5YTg4MWM5OTY0YmQ3NWFlODk5N2U3NTBhMDNjNzI2NDE3NGQwZTdjYzY1NTM5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CMVtFwdSW2fhB_hzgE669xunYKHkJTKTzBWtzqV0upM)
[Figma file](https://github.com/hackforla/expunge-assist/issues/1171#:~:text=Resources/Notes-,Figma%20file,-anitadesigns%20added)
Main: #1136

**Comment by anitadesigns** [comment]
Design updated the visual design and format to the page. We just need Content's feedback on the copy. Since there wasnt't an issue created for Content in regards to the 404 page. I created one and added it to #1138

**Comment by jyehllow** [comment]
Progress: No progress this week as we are waiting for the Content team to approve/provide feedback on copy
Blockers: Awaiting to hear from Content Team
Availability: Anita and I are available to this week to discuss further
ETA: Dependent on Content’s bandwidth

**Comment by cjankowski23** [comment]
**Progress:** Created copy and shared it with content team for feedback. 
**Blockers:** Clarity on when the 404 page appears. Will be messaging Dev and Design. 
**Availability:** I am available this week to discuss further
**ETC:** Dependent on Feedback

**Comment by anitadesigns** [comment]
404 page is complete and handed over to dev
