### ISSUE TITLE
Content Leadership Meeting

### ISSUE THREAD

**Issue by CBx3000** [hackforla/expunge-assist#1155]
# [February 8, 2024] Agenda and Notes 
### Attendees
- [ ] 

### Notetaker

- [ ] Sam
- [ ] Emma
- [ ] Curtis

### Recurring items: 
- [ ] 

### Accountability and Support Check
- [ ] Team Stand Up (15-30 minutes) 
- [ ] Sydney developed Onboarding Prework Issue Template #1062 
- [ ] Bonnie Expunge Assist Feedback Video : https://drive.google.com/file/d/1OVi22QRUebN6vj5noVyA984Hwjhl7MET/view

### New Meeting Items
- [ ] Who can take notes? 
- [ ] Review SOT Doc : https://docs.google.com/spreadsheets/d/1c_Kv_T1yER-hHckNl5zkGrlGaLNCE_AeZE6Jjmn8IK0/edit#gid=2080474274
- [ ] Roadmap and Milestone Adjustment : 
- [ ] Review V & T Doc for main Content Meeting 

### FYI
- [ ] 

### Items for next week's agenda
-[ ]

**Comment by CBx3000** [comment]
# [February 8, 2024] Agenda and Notes 
### Attendees
- [ ] 

### Notetaker

- [ ] Sam
- [ ] Emma
- [ ] Curtis

### Recurring items: 
- [ ] 

### Accountability and Support Check
- [ ] General Stand Ups (15-30 minutes) 


### New Meeting Items
- [ ] Who can take notes? 
- [ ] Copy for 404 Error Page #1171 
- [ ] FAQ expansion for Cheryl , and Issue Board review (Sydney issue tags) 
- [ ] V & T Doc Update 

### FYI
- [ ] 

### Notes from Meetings

### Items for next week's agenda
-[ ]

**Comment by CBx3000** [comment]
Start discussing content guidelines with Emma and Sam , and Identify possible first issue for Claudia 

+ 404 Page Copy ?
Create 404 Page Github Issue
Assign to writer
The Design Template is complete (Content fill in words)

+ Potential Onboarding Exercise 
Have new writer do hands on onboarding checklist (Github issue)(Get with leadership to establish what goes on the issue , and feeedback from new members to improve process )
Including Internal doc/ Timeline in Drive , SOT, 
Possible pre-survey to learn about content writer 

Possible two part onboarding dicuss with Emma , one logistic , one explaintory of team processes and systems

**Comment by emmathrash** [comment]
[March 15, 2024] Agenda and Notes

Attendees

- Sam
- Emma
- Curtis

Notetaker
 
- [ ] Sam
- [ ] Emma
- [ ] Curtis

Recurring items:
[ ]
Accountability and Support Check
 General Stand Ups (15-30 minutes)

New Meeting Items

- [ ] Onboarding process
- [ ] V&T Doc Update
- [ ] 404 issue needs to be in progress
- [ ] What does partnership mean for EA?

 
FYI
[ ]
Notes from Meeting
Items for next week's agenda
-[ ]

**Comment by emmathrash** [comment]
# [February 8, 2024] Agenda and Notes 
### Attendees
- [ ] Sam
- [ ] Emma
- [ ] Analicia

### Notetaker

- [ ] Sam
- [ ] Emma

### Recurring items: 
- [ ] 

### Accountability and Support Check
- [ ] Emma/Sam check in

### New Meeting Items
- [ ] Information architecture discussion
- [ ] Terminology and how to prioritize discussion
- [ ] Iterate on Sam & Emma's issue

### FYI
- [ ] 

### Notes from Meetings

### Items for next week's agenda
-[ ]

**Comment by emmathrash** [comment]
# [April 24, 2024] Agenda and Notes 
### Attendees
- [ ] Sam
- [ ] Emma

### Notetaker

- [ ] Sam
- [ ] Emma

### Recurring items: 
- [ ] PM/Lead Meeting Update
- [ ] Open Sync Meeting Update

### Accountability and Support Check
- [ ] Emma/Sam check in

### New Meeting Items
- [ ] #1287 
- [ ] Finalize changes for #1056, #1049, #1053 and hand-off best practices
- [ ] Chat about milestone possibilities for the content guidelines
- [ ] Update on Maria's survey idea

### FYI
- [ ] 

### Notes from Meetings

### Items for next week's agenda
-[ ]

**Comment by SamHyler** [comment]
# [May 3, 2024] Agenda and Notes 
### Attendees
- [ ] Sam
- [ ] Emma

### Notetaker

- [ ] Sam
- [ ] Emma

### Recurring items: 
- [ ] PM/Lead Meeting Update
- [ ] Open Sync Meeting Update

### Accountability and Support Check
- [ ] Emma/Sam check in

### New Meeting Items
- [ ] #598  review 

### FYI
- [ ] 

### Notes from Meetings

### Items for next week's agenda
-[ ]

**Comment by emmathrash** [comment]
# [June 20, 2024] Agenda and Notes 
### Attendees
- [ ] Sam
- [ ] Emma

### Notetaker

- [ ] Sam
- [ ] Emma

### Recurring items: 
- [ ] PM/Lead Meeting Update
- [ ] Open Sync Meeting Update

### Accountability and Support Check
- [ ] Emma/Sam check in

### New Meeting Items

- [ ] [Content Guidelines](https://github.com/hackforla/expunge-assist/issues/1286) as dependency issue
- [ ] Project board migration
- [ ] [Bonnie's Review](https://github.com/hackforla/expunge-assist/issues/1442)

### FYI
- [ ] 

### Notes from Meetings

### Items for next week's agenda
-[ ]

**Comment by mariaweissman** [comment]
Closing because no longer in use as of February 2025. See agendas below that are still used: 

- https://github.com/hackforla/expunge-assist/issues/550
- https://github.com/hackforla/expunge-assist/issues/670
- https://github.com/hackforla/expunge-assist/issues/1620
