### ISSUE TITLE
Streamline UX Designer Onboarding process

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1180]
### Overview
As we continue to grow and onboard new talent to our team, we've identified a need to streamline and enhance the onboarding experience for UX designers. Currently, the process may be fragmented or lacking clarity, resulting in inefficiencies and potential gaps in understanding for new team members. By addressing this issue and implementing improvements, we aim to create a smoother, more structured onboarding journey that equips UX designers with the necessary knowledge, resources, and support to hit the ground running and contribute effectively to our projects.

### Action Items
- [ ] Create Intake Form 
- [ ] Develop guides
   - [ ] Create a guide on the recruitment process for ui/ux designers
   - [ ] Create onboarding guide for PMs 
   - [ ] Create guide on how to handoff designs to Dev 
   - [ ] Create guide on how to use Figma 
- [ ] Create onboarding template for GitHub 
- [ ] Develop Onboarding Presentation
- [ ] #773 
- [ ] #650 

### Resources/Notes
This Issue was sparked by:

**Comment by sydneywalcoff** [comment]
Hey @anitadesigns, @vanessaavviles! Thanks again for taking this issue.

    Time for an update! Please comment the following update:
    **Progress:** What's the status of the project? What have you done and what still needs to be done?
    **Estimated Time to Completion (ETC):** When do you estimate to be finished?
    **Blockers:** Anything preventing you from finishing?

    Thanks again!

**Comment by anitadesigns** [comment]
**Progress:** We acquired two new designer but the overall Epic is still a WIP
**Estimated Time to Completion (ETC):** We won't finish this for a couple months, perhaps. 
**Blockers:** No, limited time.
