### ISSUE TITLE
Design Standardize inconsistent icons

### ISSUE THREAD

**Issue by jyehllow** [hackforla/expunge-assist#1191]
### Overview
From the credits page, we noticed that some of our icons aren't consistent in styling

### Action Items
- [x] Find a new open source icon library (?)
- [x] [**Replace all existing icons (or just the inconsistent ones) across mobile and desktop wireframes**](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=1569-24566)
- [x] Share with Design team for feedback
- [x] Prepare design hand off of all wireframes with a new icon for Dev
   - [x] add the wireframes to the design hand off page
   - [x] add comments wherever needed
   - [x] link the issue in the page
- [x] Add new icons to #1029 [in progress]
- [x] handoff to Dev
   - [x] Add new design on #1194
   - [x] Export icons as SVGs and upload to #1194 
   - [x] Remove `dependency` label
   - [x] add `ready for dev lead` label
   - [x] move to `new Issues` column on project board

### Resources/Notes
Main Issue: #1200 
Design's next steps: #1203

**Comment by eruan8888** [comment]
Found a few icon libraries to select from. Am in the process of replacing the icons of pages with icons with icons from said icon libraries.

**Comment by eruan8888** [comment]
Replaced existing icons for Material Design Icons Rounded and Sharp for the Desktop Website. Decided the next 2 icon sets to replace the website pages with will be SF Regular and iOS 17 Glyph.

**Comment by eruan8888** [comment]
Realized that I didn't need to test out multiple icon libraries and that 1 would do just fine...

**Comment by anitadesigns** [comment]
> Realized that I didn't need to test out multiple icon libraries and that 1 would do just fine...

@eruan8888 would you like to share with the UX Design team on Wednesday the library that would be best to proceed with ? I would just make sure it fits the same tone we are going with : Straightforward, trustworthy, Supportive

**Comment by eruan8888** [comment]
I'm sorry but what do we mean by "Add new design on https://github.com/hackforla/expunge-assist/issues/1194"? How do I add the design on there?
