### ISSUE TITLE
Add/replace icons to Credits page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1203]
### Dependency
- [x] #1191

### Overview
After completing #1191, our team needs to update the Credits page. The Credits page must display all illustrations and icons used throughout our expungeassist.org; therefore any icons that were removed must be replaced with the most up-to-date icons. 

### Action Items
- [x] Pull new icons from #1029 
- [ ] Add/replace icons on wireframes:
   - [ ] Credits/ XL/ All 
   - [ ] Credits/XL/ Icons
   - [ ] Credits/XS/All 
   - [ ] Credits/XS/Icons
 - [ ] Assign a Design lead for review 
    - [ ] Add [ready for design ](https://github.com/hackforla/expunge-assist/labels/ready%20for%20design%20lead) label
 - [ ] Add updated frames under the Desktop and Mobile Master pages on Figma 
- [ ] Handoff to Dev
   - [ ] Add new design on #1204 
   - [ ] Export icons as SVGs and upload to #1204 
   - [ ] Remove `dependency` label
   - [ ] add `ready for dev lead` label
   - [ ] move to `new Issues` column on project board

### Resources/Notes
- [Credits Page](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=14553-36890&mode=design&t=emBCd2wbdTsq97cU-4)
- More background on the Credits page can be found in https://github.com/hackforla/expunge-assist/issues/1010
- Main Issue: #1200
