### ISSUE TITLE
EPIC: Content Guidelines Updates

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#1286]
### Overview
The Content Guidelines are being updated, not just the voice and tone, but other parts of the Guidelines. The aim is to make them as useful as possible for Content and non-Content team members. 

PLEASE UPDATE THIS ISSUE as more content guideline issues are created.

### Action Items
- [ ] https://github.com/hackforla/expunge-assist/issues/908
- [ ] https://github.com/hackforla/expunge-assist/issues/951

### Resources/Notes
Add a link to the Content Guidelines in Figma
PLEASE NOTE: There are Content Guidelines in the drive, but this is ARCHIVED and no longer the source of truh.

**Comment by SamHyler** [comment]
Created the final issues from notes: 
- [ ] Issues to create:  introduction to content guidelines and auditing the website with the new guidelines. (remember to add labels: draft, ready for content review, label 1 request.   to each of these to be created issues)

Many need detailed added to the task list once they are ready to be worked on. We should discuss the order of these, which need to be done first and last, and which can be worked on simultaneously. I make an initial sketch, at least first and last are somewhat clear @emmathrash Also, this was a little blurry for me https://github.com/hackforla/expunge-assist/issues/1347 but created the issue since it was on the list. We can close if needed.

**Comment by emmathrash** [comment]
Added content warning strategy as part of the content guidelines

**Comment by SamHyler** [comment]
Adding new content co-leads for project tracking: @giselledizon @TechWriterMelissa

**Comment by SamHyler** [comment]
Unclear what milestone to put, do not have definitions of milestones. It's not a "feature" but rather fundamentals, ops, etc.

**Comment by raeraeicky** [comment]
@TechWriterMelissa totally fine to deprioritize. I just want to clarify one thing—the end user has been known to an extent for some time, and there has been research done on that. What we don't know is who the stakeholder is and if that narrows down the population (ie someone anywhere in CA or a specific region), and if that drastically changes what we know about the CA population who might be pursuing expungement. And of course, the tone/voice could change quite a bit depending on the stakeholder and how this is used with those end users.
