### ISSUE TITLE
EPIC: Information Architecture of EA site

### ISSUE THREAD

**Issue by sylvia-nam** [hackforla/expunge-assist#1330]
### Overview
Earlier IUT1 and IUT2 testing and ongoing work on the website's content, design, functionality, etc. point to the need for improved  usability. Separate but connected is the information architecture of the site. 

Information architecture (the organizing, order, and presentation of information on the website) brings together the needs of the user (user 1: legal aid professional, user 2: person seeking expungement directly without the help of legal aid), the context (why and when the user would seek the site, i.e., applying for expungement), and the content (reflecting the user's goals and expectations, and how to use the content).

### Action Items

Research request 
- [ ] Audit current information architecture (IA)
- [ ] Compare with final IUT report from 2022 
- [ ] Research best practices in IA specific to civic tech, digital tools, letter writing tools
- [ ] Draft and diagram new information architecture
- [ ] Discuss and collab

Main tasks for each page/feature being updated
- Content task for page updates
- Design task for page updates
- Dev task for page updates 

### Resources/Notes
- Final [IUT report](https://docs.google.com/document/d/1N0u7c1RwbxglQpLk_lIgbhDnAenMhCwNPazcNHI9aJI/edit) from 2022
- Useful blog [post](https://blog.hubspot.com/website/information-architecture) with overview of Information Architecture (its principles, examples, etc).

**Comment by SamHyler** [comment]
Content will review in line with existing priorities, added labels for tracking.

**Comment by SamHyler** [comment]
See https://github.com/hackforla/expunge-assist/issues/1348 as the first step in Content led broad IA work. Content will audit, evaluate needs, and create issues after 1348 is finished and loop in other teams as appropriate. For ex: UXR support for IA in tree testing, card sorting, or navigation research for specific areas in tandem with redesigns.
