### ISSUE TITLE
Present findings of UXR glossary to other teams

### ISSUE THREAD

**Issue by sylvia-nam** [hackforla/expunge-assist#1353]
### Overview
Present UXR findings on expungement process in CA to other teams. The findings reflect the current milestone (Stakeholder Review) and UXR priorities for that milestone (expertise in expungement in CA and content terminology).

The slide deck is another deliverable for #999.

### Action Items
- [x] UXR Lead will [draft](https://docs.google.com/presentation/d/1sJgFQiAtwdWQxRvjT3Kx-rBy2cbx7m-J_FKp2oHN39A/edit#slide=id.g2cecb737568_0_0) slide deck
- [x] UXR Lead will share slide deck with UXR PM
- [x] Revisions of slide deck
- [x] Presentation in upcoming Open Sync meeting (Friday @ 9:30am) 
- [x] Share [final](https://docs.google.com/presentation/d/1MGeAWeTl3C_Eg6rsrmzdzsc_vX2aY3YX-ODdVlDe21o/edit#slide=id.p) slide deck to repo 
- [x] Presentation in May 2024 All Teams meeting

### Resources/Notes
- Related issue #999 
- Deliverable of Issue 999: [UXR Glossary](https://docs.google.com/document/d/1D19tbPqQkFzHYF2GemsZDDdMjbUM6jh6E6ArYWS-WIo/edit#heading=h.n5tb1h4qmf0f)

**Comment by sylvia-nam** [comment]
ETC for task items 1-5 is April 29th. ETC for full issue is May All Teams.

**Comment by sylvia-nam** [comment]
Draft finished included Content team requests

**Comment by sylvia-nam** [comment]
Added final slide deck to issue

**Comment by sylvia-nam** [comment]
Will discuss with @amejiamesinas on repo for sharing and next steps

**Comment by sylvia-nam** [comment]
Added to Wiki

**Comment by sylvia-nam** [comment]
@amejiamesinas: should we keep this issue open until we can identify and write up issues on next steps?

**Comment by sylvia-nam** [comment]
All tasks completed. Will discuss with @amejiamesinas and build out of next issues before closing

**Comment by sylvia-nam** [comment]
Building out research assets based on glossary. See this issue: https://github.com/hackforla/expunge-assist/issues/1381
