### ISSUE TITLE
Write up research report based on findings from UXR glossary research

### ISSUE THREAD

**Issue by sylvia-nam** [hackforla/expunge-assist#1381]
### Overview
The UXR glossary was completed and shared in March 2024. Key findings were shared as a slide deck during Open Sync in April 2024, and All Teams in May 2024. 

The goal is to write a report based on findings from the UXR glossary research. 

### Action Items
- [ ] Draft report
- [ ] Share with PM
- [ ] Share with UXR team
- [ ] Add to relevant repos

### Resources/Notes
Related issues:
#999 
#1353 

Related docs:
[UXR glossary](https://docs.google.com/document/d/1D19tbPqQkFzHYF2GemsZDDdMjbUM6jh6E6ArYWS-WIo/edit#heading=h.n5tb1h4qmf0f)
[Slide deck](https://docs.google.com/presentation/d/1MGeAWeTl3C_Eg6rsrmzdzsc_vX2aY3YX-ODdVlDe21o/edit#slide=id.p)

**Comment by raeraeicky** [comment]
No longer needed
