### ISSUE TITLE
Jobs to be Done (JTBD) research framework

### ISSUE THREAD

**Issue by sylvia-nam** [hackforla/expunge-assist#1437]
### Overview
JTBD is a technique to help product and research teams identify the relationship of a person seeking a service (or product) as a response to their situation with the goal of achieving a particular outcome.

The goal is to focus on what our user is trying to accomplish. JTBD can be part of the matrix of other deliverables that inform Expunge Assist stakeholder conversations, research planning, design process, etc.

### Action Items
- [ ] Compile past internal research on user personas, journey maps, etc.
- [ ] Identify jobs users want to accomplish
- [ ] Analyze and define each JTBD
- [ ] List users' desired outcomes
- [ ] Write a JTBD statement
- [ ] Identify next steps in UXR and with other teams

### Background
The broader goal for the UXR team is to build a research framework to incorporate personas, user journey maps, and JTBD to build and design better solutions.

Provisional JTBD statement: A person using Expunge Assist is seeking help in writing a strong declaration (to include with a discretionary petition) to clear their record. 

The intervening steps before fulfilling that outcome are: obtaining a copy of their RAP sheet(s), clarity on eligibility with the help of legal counsel, and compiling information (GRE certificates, training certificates, evidence of sobriety, stories) to start drafting a declaration. 

The big picture motivation for expungement is access to opportunities (housing, jobs, etc).

### Resources/Notes
- Draft notes on [FigJam](https://www.figma.com/board/A1B5JqXHdov0KrRcLTyp9Q/EA---UX-Research?node-id=2519-10304&t=g6NxIGz6GJ2TUsZQ-4) 
- Useful [chapter](https://www.userinterviews.com/ux-research-field-guide-chapter/jobs-to-be-done-jtbd-framework) on JTBD (with distinctions between personas, journey maps, empathy maps)
- [Critique](https://articles.centercentre.com/jobs-to-be-done-an-occasionally-useful-ux-gimmick/) of JTBD to recognize it as one tool among many for complex tasks
