### ISSUE TITLE
review text scripts with experts 

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#145]
- [ ]  Content Log Issue #: 002/Figma comment #55/59/60

- review content with legal experts

- [ ] Content Log Issue#: 007/Figma comment #49 (added by Tierney)

- Test solutions: “I have been able to _____.”

- [ ] Content Log Issue#: 006/Figma comments #42-44

- Test solution: “This program is important to me because _____.”

- [ ] Content Log: Figma comment #85 

- Test solution: Add option for names and ages using “add more” button 
- Possible concern with asking users to provide children's names, so maybe the name text box could read: "(Optional)" - address names with expungement experts

- [ ] Content Log:  Figma comment #75: Name changes from program to recovery

- Test solution: Need to review script with legal/content experts

**Comment by yumengluo** [comment]
Dependency: needs legal experts to review the scripts.
