### ISSUE TITLE
Post Bonnie Bonnie Expunge Assist Review To-Do

### ISSUE THREAD

**Issue by mariaweissman** [hackforla/expunge-assist#1461]
### Overview
Bonnie rated the concerns in order of priority. The Must change, has to be done for the MVP, all else could happen after. Could can be rejected, it's not a requirement, just a suggestion.

### Action Items

**CONCERN M = Must Change**
- [ ] HOMEPAGE: Committed to data safety - concern M: that we are giving a blanket promise. And there are applications out there that might be installed on the computer, such as a keystroke logger, and screen recorder that employers sometimes use, that would record their visit to the site and everything that they typed.

- [ ] HOMEPAGE: A Complete Letter - concern M: concern A: how we communicate that they need legal representation.

- [ ] ABOUT US: - What Is Expunge Assist concern M: how we communicate that they need legal representation. The sentence "This is not a replacement for legal advice." can be changed to "ExpungeAssist.org is not a replacement for legal advice."

- [ ] FAQ: concern M: external links should let the user know where they are going by saying who the publisher is (example: [Clearing Your Adult Criminal Record in California: A Step-by-Step Guide](https://www.courts.ca.gov/partners/documents/ExpSBS.pdf) (publisher: Los Angeles County Neighborhood Legal Services

- [ ] FAQ: concern M: external links need to have an external link. See the comment above https://github.com/hackforla/expunge-assist/issues/1442#issuecomment-2168820868 with details and examples

- [ ] TERMS OF SERVICE: The declaration letter generator
concern M: link to the acts and add the external link icon

- [ ] CREDITS: concerns M: I could not find some of the icons referenced. We need accurate links
watch video for the details about Material UI
see https://github.com/hackforla/expunge-assist/issues/1442#issuecomment-2168844908 in comment above

- [ ] WELCOME: Before you begin
concern M: external links need to have an external link. See the comment above https://github.com/hackforla/expunge-assist/issues/1442#issuecomment-2168820868 with details and examples

- [ ] WELCOME: Before you begin
concern M: external links need to have an external link. See the comment above https://github.com/hackforla/expunge-assist/issues/1442#issuecomment-2168820868 with details and examples

- [ ] WELCOME: When you click NEXT
concern M: It takes the user to the next page, and then adds a modal on the top of that with a button that says "LET'S CONTINUE". But that creates this weird flash of a different screen, and then we see the modal. Instead, it should either show the modal on the current end of the section and then when you click LET'S CONTINUE it goes to the next section, or remove the modal, and integrate the content of the model into a page on the workflow. The reason why I have tagged this as a must, is because it's very disconcerting, If I were paranoid, it would make me feel as if I were being watched. It feels like a glitch in the matrix that only you see and generally seems unpolished and diminishes the professionalism of the rest of the site, which is outstanding.

- [ ] WELCOME: Employment and Unemployment might need some work
concern M: Do some walk throughs where you pretend you are one of these user stories (see https://github.com/hackforla/expunge-assist/issues/1442#issuecomment-2168870470 comment above). If you can't find any problems, have me review it again as those two users specifically.

- [ ] WELCOME: At the end of each section
concern M: The sentences that have been added to the app make it more likely that the letters will be perceived as formulaic. We always had some words to join things together, but it's been overly customized now. Example in Involvement: Community Service, the sentence "Serving other has been fulfilling for me".

- [ ] WELCOME: Why
concern M: The text "Thank you for considering my case." should be in the closing for spacing reasons.

- [ ] WELCOME: concern M: all the options in this section run the risk of compromising the persons privacy. There are also additional problems
concern M: Cownload .docx just downloaded something to the computer they are on. What if they forget to delete it.
concern M: Download PDF was cut off at 1 page and just downloaded something to the computer they are on. What if they forget to delete it.
concern M: Download .txt just downloaded something to the computer they are on. What if they forget to delete it.
concern M: Send Email didn't do anything for me, not sure what happens when other people use it. If it's not their computer, then it's not going to pop open their email app like it usually will on a personal computer (although that didn't work for me and I am on my personal computer)
concern: Copy to Clipboard - aren't we concerned that they will forget they have copied this to a clipboard and then the data is on the computer after we told them it wouldn't be.
What we could do is give them a set of instructions
copy to clipboard
In a separate browser tab, log into your email or personal Google Drive
paste the letter draft into your email or a Google doc.
Copy this line of text "Im Done" (now you have just replaced the the letter from your last clipped clipboard).
This of course is only true if there isn't a software that saves all items from clipboard (I have seen volunteers at HfLA with application that did that).
concern M: they may have clicked the return home button without saving, the text on the button sould say something like DONE. so the text on the button on the modal needs to be more clear, see video for details.

- [ ] WELCOME: Return Home
concern M: they may have clicked the return home button (which should be changed to DONE on the completed page or something) without saving, so the modal should confirm that they have copied the letter if they need it or go back to do so.

- [ ] TEST OF BOOKMARKING: Before you begin section of form, Keep your browser open
concern M: Please revise the text ...so be sure to keep your broswer open... to say ...so be sure to keep this browser tab open...

**Concern S = Should change**

- [ ] HOMEPAGE: What is Expunge Assist
concern S: missing commas
concern S: multiple use of the word this

- [ ] HOMEPAGE: Frequently Asked Questions
concern S: we use the word gun on a faq question on the first page and firearm on a different faq questions on the FAQ page, we should standardize and probably should use the word weapon

- [ ] ABOUT US: 
What is Expunge Assist
concern S: missing commas
concern S: multiple use of the word this
Partner with us:
concern S: add free of charge to the partner with us section

- [ ] FAQ: concern S: commas missing

- [ ] FAQ: concern S: we use the word gun on a faq question on the first page and firearm on a different faq questions on the FAQ page, we should standardize and probably should use the word weapon

- [ ] FAQ: My conviction was not in California.
concern S: Can I still use Expunge Assists, seems to be dissuading people from using it. Reword to communicate that they can use the letter it creates as a draft to share with their lawyer or legal aid clinic as a starting point.
concern S: we want to know if people outside of California are finding Expunge Assist and want to use the tool. Create an anonymous survey that they can fill out to tell us how they are using it, and what the jurisdiction is, and if there is a legal aid clinic or lawyer who has directed them to use it.

- [ ] WELCOME: Before you begin concern S: add the Roadmap to Reentry link to the FAQ where the other links or under a different question if appropriate.
Introduce yourself

- [ ] WELCOME: concern S: It's really easy for people to forget to capitalize sentences or forget periods. The software can detect if it needs to be corrected and correct it.

**Concern C = Could change**

- [ ] HOMEPAGE: Committed to data safety. concern C: iPhone and image inside are both dark, the external could be lighter
- [ ] HOMEPAGE: A complete letter. concern C: communicate that they are creating the letter
- [ ] HOMEPAGE: Frequently Asked Questions. concern C: concern C: contradiction in the explanation if something is expunged or just updated
concern C: The Button Read our FAQ, might be better if it said "All FAQs" or "More FAQs" (is actually mentioned in the FAQ review part of the video)
- [ ] ABOUT US: Why Record Clearance Matters. concern C: 144,000 might age badly, we can fix that by adding a date or at least a plus sign

- [ ] FAQ: concern C: Formatting of the FAQ page is different from the FAQs on the homepage
- [ ] FAQ: concern C: "it is often about one page" could be changed to "It is usually one page"
- [ ] FAQ: concern C: there are several places where we encourage people to get in contact with us, we can customize those links to have default subject lines. See comment above https://github.com/hackforla/expunge-assist/issues/1442#issuecomment-2168831358

- [ ] WELCOME: concern C: footer could use a tiny white pixel at the top to differentiate it from the rest of the page, which is the same color as the footer.

- [ ] WELCOME: Before you begin. concern C: when you get to the preview, it's not necessarily clear that if you are fine with how it looks, you should continue, for someone who is new to the app. I recommend user testing that (do people hesitate here? Does it prevent effective use of the application?)

- [ ] WELCOME: Involvement: Employment
concern C: The questions What do you do at this job? and How has your role at work impacted your life for the better? seem like they should be divided into two separate questions. But you might have a reason why you have not There is another part of the form that has two questions (Why have you chosen to study this? Why does it matter to you?) but those seems like the same question, where What do you do and how has it impacted your life are totally different questions. I see another section has a similar set of questions that could be divided (What do you do at this community service organization? How has your volunteer work impacted your life for the better?). I think this is worth a discussion, but ultimately it seems like it worked. It just might be adding to the cognitive load of the person answering in a way that you don't want it to.

- [ ] TEST OF BOOKMARKING: concern C: If you bookmark a page from the form filling out view and paste it into another browser tab, it does not carry any other info (AWESOME)! But when you click the back button, it shows a question without the progress bar (because there is no progress). I wonder if we couldn't just make the app not show any url change on these pages. So the page would always say expungeassist.org or expungeassist.org/welcome if its in the form. The static pages on the site should retain their URLS (example: https://expungeassist.org/about-us). Or if you went to a bookmarked link and there was no saved content in the form, after this page https://expungeassist.org/form/intro, it would kick you back to the welcome page or the homepage.

### Resources/Notes
#1442

**Comment by amejiamesinas** [comment]
Adding Items to spreadsheet [here](https://docs.google.com/spreadsheets/d/1uajit1EJKIKGd6wqQz6XC-GTYTycDo1Ea-fzAiBxCqs/edit?usp=sharing)

**Comment by emmathrash** [comment]
Finished spreadsheet, sending to team leads to look over and see where their teams may be involved

**Comment by mariaweissman** [comment]
Reviewed our Github board to ensure the milestone "00. Stakeholder Review 2.0" aligns [with Bonnie's List](https://docs.google.com/spreadsheets/d/1uajit1EJKIKGd6wqQz6XC-GTYTycDo1Ea-fzAiBxCqs/edit?usp=sharing) for MVP. All other issues will go into other milestones

**Comment by mariaweissman** [comment]
**Progress:** Ongoing epic
**Estimated Time to Completion (ETC):** Q1 2025 Goal
**Blockers:** December off, team members members transitioning

Thanks again!

**Comment by mariaweissman** [comment]
Updated this ticket to better align with [Bonnie Priority List](https://docs.google.com/spreadsheets/d/1uajit1EJKIKGd6wqQz6XC-GTYTycDo1Ea-fzAiBxCqs/edit?usp=sharing)

**Progress:** 

- 7 Dev tickets need assignees; 1 Content ticket needs assignees

@sydneywalcoff @rcpeng34 @melissareca @giselledizon 

- 4 tickets in progress (Content & Design) 

- 3 comments on hold

**Comment by mariaweissman** [comment]
Progress: 

- 3 Dev issues need assignees
-  8 issues in progress

**Comment by mariaweissman** [comment]
Progress:

- 3 dev issues need assignee
- 6 issues in progress

**Comment by mariaweissman** [comment]
Progress:

- 3 dev issues need assignee
- 5 issues in progress

**Comment by raeraeicky** [comment]
There's currently 18 tickets in the Stakeholder 2.0 milestone not listed in this issue; I'm going to review and update the milestone, this ticket, and the SoT feedback document to make them more aligned. I will do this by next All Team.

**Comment by raeraeicky** [comment]
reassigning this to you @farnazs @defnotbert @shraddhasaraf

**Comment by shraddhasaraf** [comment]
We do not have any updates on Bonnie yet
