### ISSUE TITLE
EPIC: PM Process Documentation

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1509]
### Overview
Expunge Assist has previously lost all project management processes with the offboarding of certain key members. This brought the project largely to a halt. We need to document our processes to make sure they are continued when the team changes. 

### Action Items
- [ ] create a wiki page for the PMs
- [ ] Changing a Meeting Time
- [ ] Weekly Label Check

### Resources/Notes
[PM wiki page]()

**Comment by mariaweissman** [comment]
Similar to #1664 request - will review both

**Comment by mariaweissman** [comment]
Update: This is an epic. Working on #1510 now.

**Comment by mariaweissman** [comment]
This is an EPIC. #1510 #1511 complete, working on #1512 now.
