### ISSUE TITLE
Weekly Label Check

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#1543]
### Dependency
~2023-09-11~

### Overview
We need to perform a weekly check on issues to make sure they all conform to our label and milestone schema.

### Action Items
- [ ] Check the following to make sure that they are all 0/0 (Links for checking to make sure that all issues either have a ___ or a ____ missing label)
   - [ ] [Role](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+-label%3A%22role%3A+UX+content+writing%22+-label%3A%22role%3A+research%22+-label%3A%22role%3A+product+management%22+-label%3A%22role%3A+development%22+-label%3A%22role%3A+design%22+-label%3A%22role%3A+communications%22+-label%3A%22role%3A+missing%22)
   - [ ] [size](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+13%2Bpt%22+-label%3A%22size%3A+8pt%22+-label%3A%22size%3A+5pt%22+-label%3A%22size%3A+3pt%22+-label%3A%22size%3A+2pt%22+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+missing%22+-label%3A%22size%3A+0.25%22)
   - [ ] [feature](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+-label%3A%22feature%3A+agenda%22+-label%3A%22feature%3A+Communication%2FBranding%22+-label%3A%22feature%3A+figma+content+writing%22+-label%3A%22feature%3A+figma+design+system%22+-label%3A%22feature%3A+figma+desktop+prototype%22+-label%3A%22feature%3A+figma+heuristic+evaluation%22+-label%3A%22feature%3A+Figma%2FMiro%2FFigJam+setup%22+-label%3A%22feature%3A+figma+mobile+prototype%22+-label%3A%22feature%3A+figma+partner+and+volunteer+flow%22+-label%3A%22feature%3A+figma+wireframes%22+-label%3A%22feature%3A+footer%22+-label%3A%22feature%3A+GitHub%2FProject+Board+maintenance%22+-label%3A%22feature%3A+guidelines%22+-label%3A%22feature%3A+HfLA+website%22+-label%3A%22feature%3A+letter+generator%22+-label%3A%22feature%3A+marketing+plans%22+-label%3A%22feature%3A+missing%22+-label%3A%22feature%3A+onboard+%2F+offboard%22+-label%3A%22feature%3A+One+Sheet%22+-label%3A%22feature%3A+outreach%22+-label%3A%22feature%3A+recruitment%22+-label%3A%22feature%3A+research+analysis%22+-label%3A%22feature%3A+research+plans%22+-label%3A%22feature%3A+roadmap%22+-label%3A%22feature%3A+Social+Media%22+-label%3A%22feature%3A+Style+Guide%22+-label%3A%22feature%3A+technical+standards%22+-label%3A%22feature%3A+usability+testing%22+-label%3A%22feature%3A+Whitehat%22+-label%3A%22feature%3A+wiki%22+-label%3A%22feature%3A+1Password%22+-label%3A%22p-feature%3A+About+Us%22+-label%3A%22p-feature%3A+Community+Service%22+-label%3A%22p-feature%3A+Completion%22+-label%3A%22p-feature%3A+Credits%22+-label%3A%22p-feature%3A+FAQ+Page%22+-label%3A%22p-feature%3A+Goals%22+-label%3A%22p-feature%3A+Introduce+Yourself%22+-label%3A%22P-feature%3A+landing+page%22+-label%3A%22p-feature%3A+Life+Changes%22+-label%3A%22p-feature%3A+Privacy+Policy%22+-label%3A%22p-feature%3A+Terms+of+Use%22+-label%3A%22p-feature%3A+URL+String+Parameters%22+-label%3A%22feature%3A+accessibility%22+-label%3A%22p-feature%3A+loading+screen%22+-label%3A%22feature%3A+UX+improvements%22+-label%3A%22feature%3A+code+security%22+-label%3A%22feature%3A+Data+Handing%2FPrivacy%22+-label%3A%22feature%3A+design+system%22+-label%3A%22feature%3A+dev+workflow%22+-label%3A%22feature%3A+routing%22+-label%3A%22feature%3A+Org+Updates%22+-label%3A%22feature%3A+team+operations%22+-label%3A%22feature%3A+URL+String+Parameters%22+-label%3A%22p-feature%3A+advice%22+-label%3A%22p-feature%3A+Before+You+Begin%22+-label%3A%22p-feature%3A+Contact+Form%22+-label%3A%22p-feature%3A+Finalize+Page%22+-label%3A%22p-feature%3A+footer%22+-label%3A%22p-feature%3A+glossary+tool+tip%22+-label%3A%22p-feature%3A+header%22+-label%3A%22p-feature%3A+landing+page%22+-label%3A%22p-feature%3A+404+page%22+-label%3A%22p-feature%3A+reminder+component%22+-label%3A%22p-feature%3A+Welcome%22+-label%3A%22p-feature%3A+progress+bar%22+-label%3A%22p-feature%3A+privacy+popup%22+-label%3A%22p-feature%3A+Popups%2FAffirmations%22+-label%3A%22feature%3A+documentation%22+-label%3A%22feature%3A+illustrations%22+-label%3A%22feature%3A+milestone+planning%22)
     - [ ] Add any label missing (e.g., a new feature label got added to the project, but didn't yet get added here) and update link 
   - [ ] issues that have not yet been added to [project board](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)
     - [ ] add to project board
- [ ] if changes were made, recheck to make sure all links ended up 0/0
- [ ] Audit for issues with Missing labels (to determine if we are making progress)
   - [ ] Copy this audit report format to a comment below
```
Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] milestone, ending at
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] [Icebox Issues w no dependency]()
```
   - [ ] perform audit, adding your numbers to your audit report comment
      - [ ] [Role](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+missing%22)
      - [ ] [size](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+label%3A%22size%3A+missing%22)
      - [ ] [feature](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+missing%22)
      - [ ] [milestone](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)
      - [ ] [Icebox Issues w no dependency](https://github.com/hackforla/expunge-assist/projects/1?card_filter_query=-label%3Adependency)

**Comment by vanessaavviles** [comment]
Date: 09-09-2024
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 1
   - [ ] size, ending at 3
   - [ ] features, ending at 1
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] [Icebox Issues w no dependency](0)

**Comment by mariaweissman** [comment]
Date: 2024-09-16

- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 1
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] [Icebox Issues w no dependency]()

**Comment by vanessaavviles** [comment]
Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 1
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] [Icebox Issues w no dependency]() 0

**Comment by mariaweissman** [comment]
Date: 2024-10-07
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] [Icebox Issues w no dependency]() 0

**Comment by mariaweissman** [comment]
Date: October 14, 2024
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 1
   - [ ] size, ending at 1
   - [ ] features, ending at 1
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] [Icebox Issues w no dependency]()

**Comment by mariaweissman** [comment]
Date: 2024-10-28
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] milestone, ending at
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] [Icebox Issues w no dependency]()

**Comment by mariaweissman** [comment]
Date: 2024-11-04
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0 
   - [ ] features, ending at 0
   - [ ] milestone, ending at 1
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0

**Comment by vanessaavviles** [comment]
Date: 11-11-2024
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0 
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0

**Comment by mariaweissman** [comment]
Date: 11-18-24
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0 
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0

**Comment by mariaweissman** [comment]
Date: 2025-01-03
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0 
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0

**Comment by mariaweissman** [comment]
Date: 01-21-25
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0 
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 1

**Comment by mariaweissman** [comment]
Date: 2025-01-28
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 1 
   - [ ] size, ending at 1
   - [ ] features, ending at 1
   - [ ] milestone, ending at
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] Icebox Issues w no dependency 1

**Comment by mariaweissman** [comment]
Date: 2025-02-03
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 1 
   - [ ] size, ending at 4
   - [ ] features, ending at 2
   - [ ] milestone, ending at 1
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency  4

**Comment by mariaweissman** [comment]
Date: 2025-02-05
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0 
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0

**Comment by mariaweissman** [comment]
Date: 2025-02-10 

- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0 
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0

**Comment by ExperimentsInHonesty** [comment]
### Milestones missing
There was no check (at the top) to see if issues needed the `milestone: missing` label.  I have added it and marked the three issues that didn't have milestones with the label.

### Issues that are not on the project board
- [issue tab, no:project](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue%20state%3Aopen%20no%3Aproject)
- https://github.com/hackforla/expunge-assist/issues/1695 - opened 2025-02-15 / closed as unplanned 2025-02-17
- https://github.com/hackforla/expunge-assist/issues/1657 - opened 2024-11-30 / closed as competed 2025-01-03
- https://github.com/hackforla/expunge-assist/issues/1701 - opened 2025-02-20
- https://github.com/hackforla/expunge-assist/issues/1696 - opened 2025-02-19

### Issues in the icebox with no dependency
I updated the link so that it only shows the icebox (helps reduce confusion with new pms)
- https://github.com/hackforla/expunge-assist/issues/1158

### Issues in the icebox with dependency labels but no defined dependency
- https://github.com/hackforla/expunge-assist/issues/1209
- https://github.com/hackforla/expunge-assist/issues/1518
- https://github.com/hackforla/expunge-assist/issues/409
- https://github.com/hackforla/expunge-assist/issues/1666

### Issues in the icebox with dependencies that have been resolved
- https://github.com/hackforla/expunge-assist/issues/1228 - dependency issue closed as completed 2024-05-13
- https://github.com/hackforla/expunge-assist/issues/1203 - dependency issue closed as completed 2024-10-20
- https://github.com/hackforla/expunge-assist/issues/1038 - dependency issue closed as completed 2024-05-13 & 2024-06-13

**Comment by mariaweissman** [comment]
Date: 2025-02-24
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0 
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] Icebox Issues w no dependency

**Comment by mariaweissman** [comment]
Date: 2025-03-03
- [x] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [x] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 1
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [x] Icebox Issues w no dependency 0

**Comment by mariaweissman** [comment]
Date: 2025-03-10
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] milestone, ending at
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] Icebox Issues w no dependency

**Comment by ExperimentsInHonesty** [comment]
- No one should be assigned to an issue in the icebox.   [Icebox issues with an assignee](https://github.com/orgs/hackforla/projects/77/views/1?filterQuery=status%3AIcebox+-no%3Aassignee)

**Comment by ExperimentsInHonesty** [comment]
You will notice that there has been a new issue created 18 hours ago, and it does not have a milestone missing label.  That is because that label is not in these templates and probably not in other templates
https://github.com/hackforla/expunge-assist/blob/main/.github/ISSUE_TEMPLATE/blank-issue.md
https://github.com/hackforla/expunge-assist/blob/main/.github/ISSUE_TEMPLATE/blank-issue-form.yml

**Comment by mariaweissman** [comment]
> [@mariaweissman](https://github.com/mariaweissman) You will notice that there has been a new issue created 18 hours ago, and it does not have a milestone missing label.
> 
> * [FAQ: Update language on 'Why does expungement matter to me?' #1717](https://github.com/hackforla/expunge-assist/issues/1717)
> 
> That is because that label is not in these templates and probably not in other templates https://github.com/hackforla/expunge-assist/blob/main/.github/ISSUE_TEMPLATE/blank-issue.md https://github.com/hackforla/expunge-assist/blob/main/.github/ISSUE_TEMPLATE/blank-issue-form.yml

@ExperimentsInHonesty #1717 was discussed during yesterday's meeting with @raeraeicky who was in an active slack discussion on which milestone to put for it with her team at the time of the meeting, and planning to add it or close it shortly.

**Comment by mariaweissman** [comment]
> [@mariaweissman](https://github.com/mariaweissman) You will notice that there has been a new issue created 18 hours ago, and it does not have a milestone missing label.
> 
> * [FAQ: Update language on 'Why does expungement matter to me?' #1717](https://github.com/hackforla/expunge-assist/issues/1717)
> 
> That is because that label is not in these templates and probably not in other templates https://github.com/hackforla/expunge-assist/blob/main/.github/ISSUE_TEMPLATE/blank-issue.md https://github.com/hackforla/expunge-assist/blob/main/.github/ISSUE_TEMPLATE/blank-issue-form.yml

@ExperimentsInHonesty we'll also make an issue to add that milestone missing label to the template

**Comment by mariaweissman** [comment]
2025-03-24

- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 1
   - [ ] size, ending at 2
   - [ ] features, ending at 1
   - [ ] milestone, ending at 1
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-03-24
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0 
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-03-31
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-04-07
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0 
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-04-14
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-04-21
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-04-28
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-05-05
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] milestone, ending at
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] Icebox Issues w no dependency
- [ ] Icebox Issues with assignees

**Comment by mariaweissman** [comment]
Date: 2025-05-12
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] milestone, ending at
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] Icebox Issues w no dependency
- [ ] Icebox Issues with assignees

**Comment by mariaweissman** [comment]
Date: 2025-05-19
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0 
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0 
- [ ] Icebox Issues with assignees 0

**Comment by rcpeng34** [comment]
Date: 6/16

Did you have to update the 0/0 links above? if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).

Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)

role, ending at 0

size, ending at 0

features, ending at 0

milestone, ending at 0

New Issues: 12
Icebox issues: 22
Icebox Issues w no dependency 0
Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-06-23
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by gauthamisreenivas** [comment]
Date: 2025-07-10
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0/51
   - [ ] size, ending at 0/308
   - [ ] features, ending at 0/208
   - [ ] milestone, ending at 0/245
   - [ ] Issues not on the project board 
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by mariaweissman** [comment]
Date: 2025-09-15

Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at 0
   - [ ] size, ending at 0
   - [ ] features, ending at 0
   - [ ] milestone, ending at 0
   - [ ] Issues not on the project board 0
#### Icebox issue
- [ ] Icebox Issues w no dependency 0
- [ ] Icebox Issues with assignees 0

**Comment by farnazs** [comment]
Date: 2025-09-22

- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] milestone, ending at
   - [ ] Issues not on the project board
#### Icebox issue
- [ ] Icebox Issues w no dependency
- [ ] Icebox Issues with assignees

**Comment by farnazs** [comment]
Date: 
- [x] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [x] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [x] role, ending at
   - [x] size, ending at
   - [x] features, ending at
   - [x] milestone, ending at
   - [x] Issues not on the project board
#### Icebox issue
- [ ] Icebox Issues w no dependency
- [ ] Icebox Issues with assignees
