### ISSUE TITLE
Expunge Assist: Accomplishment Summary for HfLA Website 2020-2024

### ISSUE THREAD

**Issue by mariaweissman** [hackforla/expunge-assist#1623]
### Overview

We need to write brief summaries of project accomplishments for each year of the project's life, to go on the website's accomplishments page.

### Action Items
- [x] Review the accomplishments on resource 1.02 to see how they are worded, and note the following: Accomplishments on the Hack for LA website are:
   - readable even if you don't know anything about the project
   - short
   - clearly articulated achievements that funders would care about
   -  list partners if available
- Find and review all previous onesheets
   - [x] Find all the one sheets (check Project's Google Drive resource 1.03) and link the folder to resource 1.04.03.  If there are multiple folders, create 1.04.03.01, 1.04.03.02, etc. indented under 1.04.03)
   - [x] Review all previous project onesheet drafts under 1.04 (including edit history)
- Search the project's repo for any accomplishment issues, add any links you find to a comment
  - [x] Go to the project repo issue tab (resource 1.05)
  - [x] review all closed issues, looking for details of your project's progress that you could use in your accomplishment summary, noting the accomplishment and date of completion
  - [x] Put the links relevant to that search under the below heading in chronological order
   ```
   ### Project or CoP's repo issue searches
   ```
- for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g.,)
   ```
   #### Searches
   - [Replace with what you searched for in the Filter bar]
   - [Replace with what you searched for in the Filter bar]
   - [Replace with what you searched for in the Filter bar]
   ```
- [x] Draft a brief paragraph describing what the project accomplished for each year
- Update the epic issue (resource 1.01)
   - [x] Add the following comment
   ```
   We have completed the accomplishments for 2020-2024
   ```
   - [x] Add the label `updated`
   - [x] Add the label `ready for org rep`
   - [x] Move to the questions/review column on the Team Tasks project board

### Resources/Instructions
- 1.01 [Accomplishments epic](https://github.com/hackforla/admin-accomplishments/issues/8)
- 1.02 Hackforla.org website, about page, accomplishments section: https://www.hackforla.org/about/#accomplishments
- 1.03 [Expunge Assist project Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n?usp=drive_link)
- 1.04 One Sheets: 
   - 1.04.01 [One sheet from product-management repo](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Expunge-Assist-One-Sheet.pdf)
   - 1.04.02 [One sheet link from Hack for LA website (Overview)](https://www.hackforla.org/projects/expunge-assist)
   - 1.04.03 [Folder with One sheet drafts on Expunge Assist's Google Drive](https://docs.google.com/document/d/1JFZGKxeEBWVak_GATgIt0Knyr9_gJ15CBirynebb4tg/edit?usp=sharing)
- 1.05 [Expunge Assist Issues Tab](https://github.com/hackforla/expunge-assist/issues)

**Comment by mariaweissman** [comment]
### Project or CoP's repo issue searches
- https://github.com/hackforla/expunge-assist/issues/56
- https://github.com/hackforla/expunge-assist/issues/62
- https://github.com/hackforla/expunge-assist/issues/68
- https://github.com/hackforla/expunge-assist/issues/98
- https://github.com/hackforla/expunge-assist/issues/166
- https://github.com/hackforla/expunge-assist/issues/167
- https://github.com/hackforla/expunge-assist/issues/186
- https://github.com/hackforla/expunge-assist/issues/187
- https://github.com/hackforla/expunge-assist/issues/190
- https://github.com/hackforla/expunge-assist/issues/204
- https://github.com/hackforla/expunge-assist/issues/215
- https://github.com/hackforla/expunge-assist/issues/220
- https://github.com/hackforla/expunge-assist/issues/246
- https://github.com/hackforla/expunge-assist/issues/271
- https://github.com/hackforla/expunge-assist/issues/272
- https://github.com/hackforla/expunge-assist/issues/275
- https://github.com/hackforla/expunge-assist/issues/356
- https://github.com/hackforla/expunge-assist/issues/358
- https://github.com/hackforla/expunge-assist/issues/356
- https://github.com/hackforla/expunge-assist/issues/391
- https://github.com/hackforla/expunge-assist/issues/401
- https://github.com/hackforla/expunge-assist/issues/436
- https://github.com/hackforla/expunge-assist/issues/440
- https://github.com/hackforla/expunge-assist/issues/441
- https://github.com/hackforla/expunge-assist/issues/472
- https://github.com/hackforla/expunge-assist/issues/473
- https://github.com/hackforla/expunge-assist/issues/562
- https://github.com/hackforla/expunge-assist/issues/583
- https://github.com/hackforla/expunge-assist/issues/584
- https://github.com/hackforla/expunge-assist/issues/612
- https://github.com/hackforla/expunge-assist/issues/727
- https://github.com/hackforla/expunge-assist/issues/860
- https://github.com/hackforla/expunge-assist/issues/868
- https://github.com/hackforla/expunge-assist/issues/1060 
- https://github.com/hackforla/expunge-assist/issues/1066
- [1066 includes is a Figjam board with 2023 Achievements/ Wins/ Celebrations Stickies here](https://www.figma.com/board/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?node-id=3303-9784&t=zBIR0877CVtSKx57-1)
- https://github.com/hackforla/expunge-assist/issues/1361
- https://github.com/hackforla/expunge-assist/issues/1404
- https://github.com/hackforla/expunge-assist/issues/1410
- https://github.com/hackforla/expunge-assist/issues/1442

**Comment by mariaweissman** [comment]
#### Searches
- [accomplished](https://github.com/hackforla/expunge-assist/issues?q=accomplished)
- [reflect](https://github.com/hackforla/expunge-assist/issues?q=reflect)
- [launch](https://github.com/hackforla/expunge-assist/issues?page=1&q=launch)
- [MVP](https://github.com/hackforla/expunge-assist/issues?q=mvp)
- [streamline](https://github.com/hackforla/expunge-assist/issues?q=streamline)

**Comment by mariaweissman** [comment]
HfLA is off for month of December; am going to try to complete this during that time

**Comment by mariaweissman** [comment]
**History**
In 2019, Hack for LA (HfLA) participated in a National Day of Civic Hacking (NDoCH) on the themes: justice, equity, and record clearance. Along with 80+ other volunteer civic tech organizations from around the country, HfLA identified local ways to use tech in the domain of record clearance, launching a project now called Expunge Assist. The project’s aim is to facilitate expungement for Californians with criminal records.


**2020**
11/2020 Created first Project One Sheet summarizing the work Expunge Assist (then called The Record Clearance project) had done to showcase what we’re working on actively. #56 
11/2020 Reached out to public libraries and community orgs to learn how to protect user information on public computers #62 
12/2020 Reached out to nonprofits and clinics that might be a good fit as partners #68 
12/2020 Began working with a lawyer to comb through the personal statement generator designs and copy #98


**2021**
3/2021 Began discovery research on potential partner organizations. Used the information collected through online searches to inform our outreach strategy. #186 
4/2021 Revised One Sheet #204 
5/2021 Created an Expunge Assist Communication Style Guide #167 
5/2021 Launched expungeassist.org  #220 
5/2021 Mapped out research goals and instruments with UCLA law students #246
5/2021 First introductory stakeholder meeting with UFCW expungement clinics #271
8/2021 Created a Pitch Deck for a 15 minute presentation about our personal statement generator that we can share with potential partners, investors, and new volunteers  #215

**2022**
1/2022 Conducted a comparative analysis to compare to other products in the same category #166 
1/2022 Developed an outreach plan in order to partner with organizations that work in the related areas #187 #190 
6/2022 Created an Internal Testing Final Report #562 
8/2022 Created a Site Map of EA Website #584

**2023**
11/2023 Expunge Assist Terminology Survey for Legal Professionals posted to LinkedIn


**2024**
3/2024 Updated Expunge Assist Project One Sheet #868
5/2024 Completed Accessibility Testing Epic #1060 
8/2024 Created and implemented an internal survey to identify best practices and pinpoint opportunities for process improvements, leading to enhanced efficiency and collaboration across teams #1361
7/2024 Stakeholder review of the Expunge Assist Site and Letter Generator, gathering valuable feedback and aligning expectations for future development #1442
11/2024 Developed and secured team-wide agreement on a Team Charter for the Expunge Assist project, clearly defining project objectives, measurable goals, and ensuring alignment and buy-in from all team members #1404

**Comment by mariaweissman** [comment]
2025-01-31 

- Org meeting with bonnie notes: put entire list in EA wiki
- Add to 2020: 
    - Conducted participant observation at [NDICA’s expungement clinic](https://www.thendica.org/) and conducted interviews with organizers, public defenders and pro se applicants to map user journeys
    - Met with industry experts and researchers to document the expungement process in CA
- My next steps: Create paragraphs by year in the website format and create new comments with them here

**Comment by Rabia2219** [comment]
> We have completed the accomplishments for 2020-2024 - labels added to the epic [#8](https://github.com/hackforla/expunge-assist/issues/8) [@Rabia2219](https://github.com/Rabia2219)

@mariaweissman 
Thanks for the update...
P.S. Did you mean to link to issue number 8?

**Comment by mariaweissman** [comment]
> > We have completed the accomplishments for 2020-2024 - labels added to the epic [hackforla/admin-accomplishments#8](https://github.com/hackforla/admin-accomplishments/issues/8) [@Rabia2219](https://github.com/Rabia2219)
> 
> [@mariaweissman](https://github.com/mariaweissman) Thanks for the update... P.S. Did you mean to link to issue number 8?

Sorry, the epic is on a different board so it links differently - here's the direct link: https://github.com/hackforla/admin-accomplishments/issues/8

thanks!

**Comment by ExperimentsInHonesty** [comment]
This [list of accomplishments](https://github.com/hackforla/expunge-assist/issues/1623#issuecomment-2628442130) is missing 

- when we created a servicemap for UCLA's record clinic partnership 
   - https://github.com/hackforla/expunge-assist/issues/298 
   - https://github.com/hackforla/expunge-assist/issues/286

**Comment by mariaweissman** [comment]
> [@mariaweissman](https://github.com/mariaweissman) This [list of accomplishments](https://github.com/hackforla/expunge-assist/issues/1623#issuecomment-2628442130) is missing
> 
> * when we created a servicemap for UCLA's record clinic partnership
>   
>   * [Create Process Map for A New Way of Life #298](https://github.com/hackforla/expunge-assist/issues/298)
>   * [Create Service Design/Process Map in Miro #286](https://github.com/hackforla/expunge-assist/issues/286)

Hi Bonnie @ExperimentsInHonesty, what year and accomplishment would you like to state for this? I'm reviewing these two issues but not finding the details to identify a specific accomplishment. 

I see in [this report](https://drive.google.com/file/d/13BQa_5pf-BWakmKN0ve7aa0ZHH6J3xfm/view) it states "NDICA clinic interviews

The team interviewed 8 people who attended an expungement clinic in the Fall
of 2019. The clinic was hosted by NDICA and the LA Public Defender’s Office in [part of LA]."

**Comment by ExperimentsInHonesty** [comment]
@mariaweissman it looks like this is around the date.  I remember we got it done pretty quickly, so 2021

>[apurvabarve](https://github.com/apurvabarve) assigned [apurvabarve](https://github.com/apurvabarve), [myrandi](https://github.com/myrandi), [yumengluo]https://github.com/yumengluo) and ghost [on Jul 26, 2021](https://github.com/hackforla/expunge-assist/issues/298#event-5069859763)

And the Service map is here https://miro.com/app/board/o9J_l7_CQ2I=/  

Please also create a new issue to see if we own it
- Try to log in using the email address of the project or if the project also has a Gmail, try that too.  If that does not work, we probably want to ask the owner to transfer ownership.  But ill help you with that, because we need to make sure we have them send it to the correct account.

**Comment by ExperimentsInHonesty** [comment]
@mariaweissman I believe this is a different accomplishment

>I see in [this report](https://drive.google.com/file/d/13BQa_5pf-BWakmKN0ve7aa0ZHH6J3xfm/view) it states "NDICA clinic interviews

>The team interviewed 8 people who attended an expungement clinic in the Fall
of 2019. The clinic was hosted by NDICA and the LA Public Defender’s Office in [part of LA]."

**Comment by ExperimentsInHonesty** [comment]
@mariaweissman once you have updated the accomplishments, ask me to review in the product-management channel plz.

**Comment by mariaweissman** [comment]
2020

Conducted participant observation and interviews at NDICA’s expungement clinic to map user journeys and collaborated with experts to document California's expungement process.

11/2020 created the first Project One Sheet to summarize our work, and reached out to public libraries and community organizations to learn how to protect user data on public computers. Began working with a lawyer to refine the personal statement generator.

2021

5/2021 launched expungeassist.org and held our first introductory stakeholder meeting with UFCW’s expungement clinics to explore potential partnerships and expand impact.

8/2021 designed a service map for UCLA’s record clinic partnership.

2023

11/2023 posted the Expunge Assist Terminology Survey for Legal Professionals on LinkedIn to engage the legal community and gather valuable feedback.

2024

5/2024 updated the Expunge Assist Project One Sheet to reflect our progress. 7/2024, completed alpha testing to validate the platform’s functionality.

**Comment by mariaweissman** [comment]
> 
> Please also create a new issue to see if we own it
> 
> * Try to log in using the email address of the project or if the project also has a Gmail, try that too.  If that does not work, we probably want to ask the owner to transfer ownership.  But ill help you with that, because we need to make sure we have them send it to the correct account.

Hi @ExperimentsInHonesty , we do own it via the recordclearance@hackforla.org email address. The miro board is locked beyond that in terms of adding additional email addresses because it's a free account. Would you like an issue made for the EA board that states all this?
