### ISSUE TITLE
Output generated statement directly into MC-031 Attached Declaration form

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/expunge-assist#270]
### Overview
The folks who run expungement clinics with the UFCW-324 labor union said that our statement generator would be most useful to them if it put the generated statement/declaration directly into the [MC-031 Attached Declaration](https://fill.io/Form-MC-031-ATTACHED-DECLARATION) form used by the CA Court system.

### Action Items
- [ ] We need to add a few more fields to our forms in order to fill out the MC-031 form completely 
   - [ ] PLAINTIFF/PETITIONER
   - [ ] DEFENDANT/RESPONDENT (?)
   - [ ] CASE NUMBER
- [ ] Collaborate with the design team to determine the best way to add these questions to the product.
- [ ] Research how to automatically fill out a fillable PDF from our web app
- [ ] Connect form responses to appropriate MC-031 fields
- [ ] Quality assurance checks – determine if additional field validation is necessary for text to fit into MC-031 form

### Resources/Instructions
- Related issue: See sample declarations: https://github.com/hackforla/expunge-assist/issues/512

- [MC-031 Attached Declaration form](https://fill.io/Form-MC-031-ATTACHED-DECLARATION) – The form used by CA expungement clinics to include a personal statement that is longer than a paragraph.
- [CR-180 Petition for Dismissal](https://www.courts.ca.gov/documents/cr180.pdf) – The form used by CA expungement clinics to petition for record clearance. See question 2c, which references the MC-031 form:
> Please note: You may explain why granting a dismissal would be in the interests of justice. You can provide that information by writing in the space below, or by attaching a letter or other relevant documents. If you need more space for your writing, you can use the Attached Declaration (form MC-031) and attach it to this petition.

**Comment by brandohayes** [comment]
Product will need to discuss this issue during the next meeting to see if this is still relevant.

**Comment by brandohayes** [comment]
Is this a significant issue that we want to tackle as someone could simply copy and paste the statement into the form? Also, would it be good for us to add this function only for CA when this could be a product used for multiple states?

**Comment by thomasdemoner** [comment]
sort out details and decide what to do with it.

**Comment by anitadesigns** [comment]
Requires more research for us to proceed with this task

**Comment by amejiamesinas** [comment]
Team revisited issue. Research team working on understanding user journey, and will continue to update.

**Comment by SamHyler** [comment]
NOTE! Pick up this issue in JAN 2024 and make decisions going forward

**Comment by sylvia-nam** [comment]
I'll add this issue to the next UXR meeting on 3/15/24 to discuss with the team. Based on that discussion, we can pursue next action items accordingly and as necessary. My recommendation is to close the issue but will discuss with UXR and other team PMs and Leads.

Preliminary notes:
1. This issue is pending Design input: https://github.com/hackforla/expunge-assist/issues/512 but some insights from that issue:

There is no standard format for the declaration. 

Successful samples show that some petitioners write the letter by filling MC-030 directly, or attach their letter to MC-031 without filling it in (by attaching it as a personal letter on a Word doc to either MC-030 or MC-031). None of the samples analyzed in Issue 512 were populated directly into MC-031. 

This differs from how Issue 270 is described here, as does the identified need to output the letter into a MC-031 form. 

2. Root & Rebound provides free legal services to people seeking expungement in CA and they train their volunteers on conducting the intake which precedes letter writing. Based on the "Record Cleaning 101" webinar by Root & Rebound on 2/29/24:

The SAME letter can be used across expungement petitions. Why? A person needs to submit separate petitions for each record he/she/they are seeking to clear. The court will see the person's rap sheet, which presents a person as a sum of their parts (record 1 of crime a, record 2 of crime b, etc.) or as a history of interaction with law enforcement and the criminal justice system.

In contrast, the letter presents the person as a whole with a present and a future. The focus of the letter is the person's rehabilitation (which is also in the "interests of justice") and not the specifics of the crime and case per se.

There is no need to write separate letters for each petition, even as each petition needs a letter. 

On a logistical, legal, technical level, then, there are some unintended consequences of generating the statement on MC-031: 
1) confusing the user (either by implying that they must write multiple and thus different letters), 
2) putting EA in muddy legal waters by offering legal advice (which is illegal) - for ex, needing to validate the correct case number on a RAP sheet - versus providing legal information (which is legal), 
3) the need to think through the existing features on the EA site that currently don't exist or need to be built

3. Based on collab [meeting](https://github.com/hackforla/expunge-assist/issues/618#issuecomment-1981645222) on 3/8/24 between Design x Content x UXR , there was a discussion of changing the features of the existing letter generator (spec. pop-ups). Overhauling the letter generator req Dev work and input.

**Comment by sylvia-nam** [comment]
Based on PM meeting on 3/11/24, issue is closed.
