### ISSUE TITLE
Research Summary

### ISSUE THREAD

**Issue by H1Angela** [hackforla/expunge-assist#4]
### Overview
Given the amount of data available we need a summary of all documentation and research on the record clearance project. 

### Action Items
Review the following doc:
- [ ] CA Crime Stat's #5 
- [ ] Court Rep Evals #6 
- [ ] Interviews with NDICA #11 
- [ ] Omar Convo #12 
- [ ] Pre-clinic Call - NDICA #13 
- [ ] Legal & Online Research #14 
- [ ] RCP Client Demo #15  
- [ ] Speed Screening Research  #16 
- [ ] Sticky-notes from NDICA #17 

 User Research (7 doc's in folder)
 1. - [ ] [Clinic Service Blue Print_NDICA](https://drive.google.com/file/d/1rKkWcZMFu_VvPbqwDKQvG4xT6eYREBxL/view?usp=sharing)
 2. - [ ] [NDICA Clinic Attendee Breakdown variable Mapping](https://drive.google.com/file/d/1u4NFO9liTVu9ow1TUxCrx2ZH40_vkLx0/view?usp=sharing)
 3. - [ ] [ NDICA Clinic Attendee Personas 201919](https://docs.google.com/document/d/1zD-V5vye8a4ZrmroxSEdHLJmrYLELHj7e5WRDbkiEyU/edit?usp=sharing)
 4. - [ ] [NDICA Clinic Attendee Personas](https://drive.google.com/file/d/1GaxH09ICsGzHfB6ExzfZxFa-V7y1zPrc/view?usp=sharing)
 5. - [ ] [Personas for KYR site](https://docs.google.com/document/d/1qfJzVrY4ZbYiC9w--6LJ-lRhFXBcyMc-5BUGyQgful4/edit?usp=sharing)
 6. - [ ] [RC Petition Application Personas + Segment - 2017](https://drive.google.com/file/d/1TdHOnpQnXE41-N0aCxghk4aBKNo-SHXX/view?usp=sharing)
 7. - [ ] [KYR Site UX -- Journey Mapping + Info](https://drive.google.com/open?id=1fG4Q3NWDfIuA6X5vkHND-dcu4bR1FSD7)  
 8. [Expungement Clinic Research](https://drive.google.com/drive/u/0/folders/1tTYanDJVg-RPFdIDi2f3K3krx5V9-U-N) (2 doc's in folder)
      - [ ] [NDICA -- Pre-Clinic Call](https://drive.google.com/open?id=1CAh6SnAXfdO7Ircwm4kW3LBQhw7U7EMaNdJF7tbYc3s)
      - [ ] [San Jose Notes on Record Clearance Clinics - Omar Arauza](https://drive.google.com/open?id=1emeYUwvKyj_S3N0YKv3loFofTxaNxz4f_v-sICRFafk)

- [ ] [NDoCH Photos](https://drive.google.com/open?id=10LPDAoZB0D1TO-b1bwvAUfxhHXYfSr8B) (6 images in folder)
- [ ] [CfA Record Clearance Team -- Research & Guidance](https://drive.google.com/open?id=0B33gE8kWJbwtVmgtOU5oY3drUU9IMHFudTdodGpXOE9LTUJN) (6 files in folder)
 1. - [ ] [1076 Eligibility and Proc](https://drive.google.com/open?id=0B33gE8kWJbwtSUF1YVdPMUhJcVNidjg3aU5aREZOVWMxUi13)
 2. - [ ] [Aditi Joshi](https://drive.google.com/open?id=1WaENRGqHwSYtv7ZFSgUNt1xCpMwY4KZgt3GrNIQfTps)
 3. - [ ]  [Brigade-CfA Collaboration](https://drive.google.com/open?id=1-6XFcuhQpv-pBi-QWUcV_kkXFfvJktC0qp0aiJv4KA8)
 4. - [ ]  [Copy of Aditi Joshi (CfA UX) docs & links](https://docs.google.com/document/d/1mIAzJgxAiKTVTkcfi2t6qQ4xJOn7dWhCp-g21jJaBeI/edit?usp=sharing)
 5. - [ ]  [IL example -records_expungement](https://drive.google.com/file/d/1BMUigo4i-9-hsXb4NCt88M1fi4P0FqbJ/view?usp=sharing)
 6. - [ ]  [MI_Process.pdf](https://drive.google.com/file/d/0B33gE8kWJbwtVmgtOU5oY3drUU9IMHFudTdodGpXOE9LTUJN/view?usp=sharing)

Outcome: 
- [ ] We need to decide a format #9 for the summary page
- [] Please add a heading/title so we can hyperlink and create an outline
### Resources/Instructions
[The Google drive link](https://drive.google.com/drive/u/0/folders/1hBhOeNyjjEaHcWAKSu9eW--FF9HnKNqe)

[Work will be put here](https://docs.google.com/document/d/1oUgN7vT0M-nkMBj68ugPOvvZSgngkL8aRMfX2zF9olk/edit?usp=sharing)
