### ISSUE TITLE
Partnership Database: Clean-Up 1/18/22

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#430]
#Partnership Database: Clean-Up 
### Overview
The research team conducts an inventory of the partnership database

### Tasks:
- [ ] Clean up and organize partnership database 
   - [x] Add information of past outreach (when/who/how contacted in the past)
   - [x] Create a legend for the database 
   - [x] Create 'History of Partnership' tab and move all stakeholders we spoke with in the past

[Partnership Database](https://docs.google.com/spreadsheets/d/1hTOXq377vMAcacV07oRbzXEJdLqvnn9IV5xImHaIeEg/edit#gid=1577703848)
