### ISSUE TITLE
Legal Clinics Database for Prospecting Survey and Other Outreach

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#445]
### Overview
The research team need to begin developing new contacts in the database for future outreach. Specifically, now (September 2022) we are planning to send out Prospecting Surveys to legal clinics in CA as a Wave 1 outreach. 

For each legal clinic, law school, or other legal professional organization, we need contact info ready for sending out the survey. We currently have lists of possible [Law Schools](https://docs.google.com/document/d/1sXi6wcM0byP2bF53Ux0DEAjnm-0N1Lr5bH4ccFZeE5s/edit) and [Pro Bono Legal Organizations](https://docs.google.com/document/d/1ZKHUevH3aLzOizQiyR45zhGpIzNaQKfJOlAQFuMHEkk/edit#) to look into. 

For each list, we need to look at each website and  figure out who to email (an administrator, or it might just be an info@ address) to ask about a listserv, or something similar. Once contact information has been identified, we need to add the website, org name, and contact info to the [Partnership Database Master list](https://docs.google.com/spreadsheets/d/1hTOXq377vMAcacV07oRbzXEJdLqvnn9IV5xImHaIeEg/edit#gid=1577703848).

### Tasks:
- [x] review the legend for the database, existing contacts, and outreach efforts 
- [x] develop list of free legal clinics that provide expungement services in CA for Wave 1 prospecting survey
- [ ] Expand to other states for Wave 2 (TBD)

### Working Documents:

[Partnership Database Master](https://docs.google.com/spreadsheets/d/1hTOXq377vMAcacV07oRbzXEJdLqvnn9IV5xImHaIeEg/edit#gid=1577703848)

[Legal Orgs/Groups to look into](https://docs.google.com/document/d/1ZKHUevH3aLzOizQiyR45zhGpIzNaQKfJOlAQFuMHEkk/edit#)

[Law Schools to look into](https://docs.google.com/document/d/1sXi6wcM0byP2bF53Ux0DEAjnm-0N1Lr5bH4ccFZeE5s/edit)

**Comment by ValeriyaMetla** [comment]
For now we can keep adding legal clinics from California, when we know more about research across the states - can start adding from other states

**Comment by yumengluo** [comment]
The step-by-step guide for the outreachs is mostly finished. I think we will just need to get feedback from the team and Bonnie and finalize it.
