### ISSUE TITLE
Usability testing: create task list

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#470]
### Overview
Create task list for usability testing.  This is to focus on what issues a user could encounter when using the application  
### Action Items
- [x] create task list application for someone who is going through the expungement process and wants a letter generated
- [x] create questions for legal professionals that would use application with legal clinic clients 
- [x] create tentative text for task list
- [x] Review task list with team 
   - [x] Make changes requested
- [x]  Remove Dependency from #444
- [x]  Close this issue when complete

### Working Draft 
Go to the Working Draft, find the section for screener and your name assigned, make changes: #442
