### ISSUE TITLE
Setting Up Milestones in GitHub

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/expunge-assist#560]
### Overview
We need to create a roadmap that includes the milestone list to help with product prioritisation, project monitoring and for the team to know what each task builds up to.

### Action Items
- [x] Create milestone list using OCS template and project one sheet as examples
- [x] Meet with Bonnie to create list
- [x] Add Milestones to Repo
- [x] Add Milestones to each issue

#### Examples
- [OCS Project Roadmap Spreadsheet](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)
- [OCS Project Roadmap Issue](https://github.com/hackforla/guides/issues/36)
- [Milestones in GitHub](https://github.com/hackforla/guides/milestones?direction=asc&sort=title&state=open)

#### EA Roadmap
[Spreadsheet](https://docs.google.com/spreadsheets/d/1OmVXe82o33GtxjM_hxf7LdBeFQ5IZgtWhoFC6c9eU7k/edit#gid=0)
