### ISSUE TITLE
UX Research Team Meeting Agenda

### ISSUE THREAD

**Issue by jbsteinhardt** [hackforla/expunge-assist#568]
### Overview
Gather all items team members want to propose for this weeks' agenda.

### Action Items
Add comment to this issue with your proposed agenda item. If item warrants an issue of its own please start a [new issue]
# 5/26/22 Agenda and Notes
### Attendees
- [ ] 
### New Meeting Items
- [ ] Finishing Final Report on Internal Testing: review and discuss recommendations; last additions
- [ ] How to make an issue in GitHub; how to manage the board (someone should take notes on this for documentation)
### FYI
- [ ] 

### Task Items
- [ ] 
### Items for next weeks agenda
- [ ] 

### Accountability and Support Check
- [ ] Review assignments for each team member
