### ISSUE TITLE
EA: All-Team Meeting Agenda

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#602]
## This issue tracks the running agenda for the All-Team Meeting

_Link for each week's Agenda comment below:_
[2022.10.18](https://github.com/hackforla/expunge-assist/issues/602#issuecomment-1281665821)
[2022.07.12](https://github.com/hackforla/expunge-assist/issues/602#issuecomment-1180992830)
[2022.07.26](https://github.com/hackforla/expunge-assist/issues/602#issuecomment-1190948947)

```
# [Date] Agenda and Notes

### Prework
- [ ] Representative from each team 
- [ ] Product Defined Agenda here (Recurring Items/New Meeting Items)
- [x] Reminder to team in Slack w/ topics
- [ ] Any special team-wide shares? (e.g. presentation)
### Roll Call

### Recurring items: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates from each Team (UXR/Dev/Content/Design/Product)
- [ ] Overall Project Direction (Product)

### New Meeting Items
- [ ] 
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
   - 
- [ ] 
   - 
- [ ] 
   - 

### Task Items
- [ ] @ 
- [ ] @ 
### Items for next month
- [ ]

**Comment by jamiesiu** [comment]
# [2022.07.12] Agenda and Notes

### Prework
- [ ] Representative from each team 
- [ ] Product Defined Agenda here
- [ ] Reminder to team in Slack w/ topics

### Roll Call
@ValeriyaMetla @thomasdemoner 

### Recurring items: 
- [ ] New Teammates Intros / Team Roster Updates
- [ ] High Level Updates from each Team (UXR/Dev/Content/Design/Product)
- [ ] Overall Project Direction (Product)

### New Meeting Items
- [ ] Moscow Exercise
- [ ] Prioritizing Usability Feedback
- [ ] PM Timeline / Rough sense
- [ ] 
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI

### Notes from Meeting

### Task Items

### Items for next meeting agenda

**Comment by ValeriyaMetla** [comment]
# [7.26.22] Agenda and Notes

### Prework
- [ ] Representative from each team 
- [ ] Product Defined Agenda here
- [ ] Reminder to team in Slack w/ topics
### Roll Call

### Recurring items: 
- [ ] New Teammates Intros / Team Roster Updates
- [ ] High Level Updates from each Team (UXR/Dev/Content/Design/Product)
- [ ] Overall Project Direction (Product)

### New Meeting Items
- [ ] Checking prioritization of internal usability feedback
- [ ] Product & Team Leads Meetings
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI

### Notes from Meeting

### Task Items

### Items for next meeting agenda

**Comment by ValeriyaMetla** [comment]
@thomasdemoner @jamiesiu We should assign team members from research, design, and development. We can take notes here the next meeting, I already created an agenda.

**Comment by jamiesiu** [comment]
# [2022.10.17] Agenda and Notes

### Prework
- [ ] Representative from each team 
- [ ] Product Defined Agenda here (Recurring Items/New Meeting Items)
- [ ] Reminder to team in Slack w/ topics
### Roll Call

### Recurring items: 
- [ ] New Teammates Intros / Team Roster Updates
- [ ] High Level Updates from each Team (UXR/Dev/Content/Design/Product)
- [ ] Overall Project Direction (Product)

### New Meeting Items
- [ ] 
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI

### Notes from Meeting

### Task Items

### Items for next meeting agenda

**Comment by jamiesiu** [comment]
# [2022.11.15] Agenda and Notes

### Prework
- [ ] Representative from each team 
- [ ] Product Defined Agenda here (Recurring Items/New Meeting Items)
- [x] Reminder to team in Slack w/ topics
### Roll Call

### Recurring items: 
- [ ] New Teammates Intros / Team Roster Updates
- [ ] High Level Updates from each Team (UXR/Dev/Content/Design/Product)
- [ ] Overall Project Direction (Product)

### New Meeting Items
- [ ] 
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI
- [ ] 

### Notes from Meeting
- 
   - 
- 
   -   

### Task Items
- [ ] @ 
- [ ] @ 
### Items for next meeting agenda
- [ ]

**Comment by jamiesiu** [comment]
# [2023.01.10] Agenda and Notes

### Prework
- [ ] Representative from each team 
- [ ] Product Defined Agenda here (Recurring Items/New Meeting Items)
- [x] Reminder to team in Slack w/ topics
- [ ] Any special team-wide shares? (e.g. presentation)
### Roll Call

### Recurring items: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates from each Team (UXR/Dev/Content/Design/Product)
- [ ] Overall Project Direction (Product)

### New Meeting Items
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] Team Planning Highlights
- [ ] Open Q&A
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
   - 
- [ ] 
   - 
- [ ] 
   - 

### Task Items
- [ ] @ 
- [ ] @ 
### Items for next month
- [ ]

**Comment by jccchurch** [comment]
# [2023.05.09] Agenda and Notes

### Prework
- [ ] Representative from each team 
- [ ] Product Defined Agenda here (Recurring Items/New Meeting Items)
- [x] Reminder week before to team in Slack
- [ ] Reminder week of to team w/ topics in Slack
- [ ] Any special team-wide shares? (e.g. presentation)

### Roll Call
- [ ] Volunteer for note-taking?

### Product: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] Overall Project Direction (Product)

### UXR: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] Overall Project Direction (Product)

### Content: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] Overall Project Direction (Product)

### Design: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] Overall Project Direction (Product)

### Dev: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] Overall Project Direction (Product)

### New Meeting Items
- [ ] Team Planning Highlights
- [ ] Open Q&A
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
   - 
- [ ] 
   - 
- [ ] 
   - 

### Task Items
- [ ] @ 
- [ ] @ 
### Items for next month
- [ ]

**Comment by jccchurch** [comment]
# [2023.06.06] Agenda and Notes

### Roll Call
- [ ] Volunteer for note-taking?

### NEW: Expunge Assist Product Demo
- [ ] We are putting together a Product Demo / Pitch Deck for review with Bonnie
- [ ] We will meet with Bonnie in July (after her hiatus)
- [ ] Goal is to get our Pitch Deck to a level where we can approach potential partners
- [ ] Identify our User Stories

### Product: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] Overall Project Direction (Product)

### UXR: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] IUT2 Testing update - tests are being scheduled for last 2 weeks of June

### Content: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 

### Design: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 

### Dev: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 

### New Meeting Items
- [ ] Team Planning Highlights
- [ ] Open Q&A
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
   - 
- [ ] 
   - 
- [ ] 
   - 

### Task Items
- [ ] @ 
- [ ] @ 
### Items for next month
- [ ]

**Comment by amejiamesinas** [comment]
# [2023.08.04 & 2023.08.08] Agenda and Notes

### Roll Call
- [ ] Volunteer for note-taking?

### NEW: 2023 Roadmapping 


### Product: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 
- [ ] Overall Project Direction (Product)

### UXR: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates  

### Content: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 

### Design: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 

### Dev: 
- [ ] New Teammates Intros / Team Roster Updates / Celebrations
- [ ] High Level Updates 

### New Meeting Items
- [ ] Open Q&A
- [ ] Carry over to next meeting anything we didn't get covered this week
   - [ ] Make next meeting agenda

### FYI / Announcements
- [ ] 

### Notes from Meeting

**Comment by sylvia-nam** [comment]
We are merging this All-Team Meeting Agenda issue #602 with #670 EA Team Planning Agenda.

**Comment by raeraeicky** [comment]
@mariaweissman since this is a historical agenda, I'll close this issue.
