### ISSUE TITLE
MoSCoW for Content

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#610]
### Overview
Do MoSCoW exercise together at team meeting in preparation for next sprint before usability testing round 2. 

### Action Items
- [x] Decide priority of issues 
- [x] Arrange in Figjam
- [x] Sync between Github issues, and [sheet](https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit#gid=0). (Sam)

### Resources/Instructions
Google sheet (https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit#gid=0)

[Figjam](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Internal-Usability-Pilot-Results-(Design)?node-id=0%3A1)
