### ISSUE TITLE
Create Product Roadmap

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#615]
### Overview
We need to create a product roadmap using HfLA Guide.  It will support PMs in better guiding the team and product development. 

### Action Items
- [x] Review HfLA Guide on how to create Product Roadmap
- [x] Create a draft in Miro Board 
   - [x] Review with PMs, Leads
- [x] Review and align with Milestones in Excel and GitHub #560  
- [x] Use for Monthly Planning Meeting #670 

### Current Version
[Sprint Planning Meeting MIRO Board, August  + September 2022](https://miro.com/app/board/uXjVOgYceoQ=/)

### Resources/Instructions
[HfLA Guide: Product Roadmaps](https://docs.google.com/document/d/1sZHHfqXoui4zsMQ2l_O3TRIJcXQnyOO-bF-KY9jl4qM/edit)
[Examples MIRO Board](https://miro.com/app/board/uXjVOoFeo-Q=/)

**Comment by ValeriyaMetla** [comment]
@jamiesiu @thomasdemoner I am moving this backlog if we need to modfy roadmap we have in Miro board for planning meeting. All relevant issues are also attached.
