### ISSUE TITLE
Create User Journeys 

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#616]
### Overview
In response to user testing, Content & Design are collaborating on creating an onboarding and demo sequence for users to understand the product better and more quickly. One of those elements includes an understanding of the user journey through expungement as a whole. We are requesting a compiled user journey from the UXR team, which the Design and Content team will then convert into a target user facing webpage that explains the user journey in a visual. For now we are focusing on California expungement processes at a fairly high level. HIGH PRIORITY as this page is being created before internal user testing 2 and needs to be designed and implemented before then. 

### Action Items
- [x] Gather examples of existing user journey and user journey-like maps that have already been created (some are linked in the resources below)
- [x] create user journey for people who are going through the expungement process in California
- [x] Discuss in Design and Content collaboration
- [x] Handover to Design and Content

### Resources/Instructions

User Journey on Figma file is located [here](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A34). 
Nikita's work on the user journey is in [this google doc.](https://docs.google.com/document/d/13jDSgaYyZzjD1UlevRQnOn2ddIvlGUJYqTx6Y2uubjA/edit)

Resources for those creating the user journey: 

https://myprop47.org/wp-content/uploads/2015/03/Reclassification-8.5x11-FINAL.pdf
https://miro.com/app/board/o9J_l7_CQ2I=/
Short example created by Content team Fall 2021 (created on a private miro board, so linking screenshot here for future use): ![legal user journey by Lori fall 2021 expunge assist](https://user-images.githubusercontent.com/87077650/184428362-56d71b12-dd28-47a2-8087-f9e69e09f021.png)
https://www.clearmyrecord.org/

**Comment by anitadesigns** [comment]
https://github.com/hackforla/expunge-assist/issues/613 is dependent on the first point

**Comment by ValeriyaMetla** [comment]
@yumengluo please attach the right document where the roadmap lives. I would like to review but there is no link

**Comment by yumengluo** [comment]
@ValeriyaMetla https://www.figma.com/file/bL8FpRGLiABZ2CRTMh44uz/Untitled?node-id=2%3A13 Here is the link to the road map of the expungement process. @SamHyler mentioned that she will move this map to the team's Figma profile.

**Comment by SamHyler** [comment]
> @ValeriyaMetla https://www.figma.com/file/bL8FpRGLiABZ2CRTMh44uz/Untitled?node-id=0%3A1 Here is the link to the road map of the expungement process. @SamHyler mentioned that she will move this map to the team's Figma profile.

Thank you Yumeng! I've added it to a page in Figma (see resources section above) for now, will update this github issue if it gets moved elsewhere

**Comment by amejiamesinas** [comment]
@dmeyers1348 For your reference on the current issue
