### ISSUE TITLE
Document and Refine EA Research Roadmap and Internal Wiki

### ISSUE THREAD

**Issue by mchai1218** [hackforla/expunge-assist#723]
### Overview
Crafting a research roadmap will enable our team to map out our research agenda and priorities. Building a research repository/Wiki not only enables us to store important research-related documents but also creates transparency for cross-functional communication. 

This effort is a direct response to Bonnie's pending approval of the survey studies (#714 ). It also addresses early concerns of documentation in #401  and #473 .

### Action Items

- [x] Create a [research roadmap](https://docs.google.com/document/d/1OJ0LD-oIICMz1kGsX6p7oYtPywYcWwvl6cmaW5gn6wc/edit#)
- [x] Build an [internal Wiki](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
- [ ] Review, discuss, and refine the research roadmap 
- [ ] Review and refine the internal Wiki
- [ ] Move the internal Wiki public to all
- [ ] Update the research roadmap after each study
- [ ] Update the Wiki after each study

**Comment by SamHyler** [comment]
I have now updated the wiki from IUT 1 - IUT 2. Many links were incorrect or missing. I added a Github issue column since they are important sources of truth and tracking. A lot/most relevant documents are linked in the Git issues and are another way of finding information. I also added links to the entire folders for many rather than just the docs so that we could list just main docs and the folder to find the rest of the information. 

I suggest we delete the column that says "length in minutes" as it is nonsensical.

**Comment by kelseylondon** [comment]
Thanks @SamHyler! I take responsibility for the missing links from IUT1 - it was my task to review it, and I should have dug further into the Github issues. Thank for linking the main folders/links and for creating the Github issues column. 

I have deleted the "length in minutes" column. My understanding is that the column was a holdover from the Internships wiki we were using as a template, but I agree that it does not make sense for our project.

**Comment by SamHyler** [comment]
Thanks @kelseylondon ! Sorry for overstepping tasks, I literally only read "review wiki" and nothing more and just didn't even realize it was split between people. 
There are probably a few more Github issues that could be linked or presented better for IUT1, there were a lot of them!

**Comment by kelseylondon** [comment]
No worries at all! I seriously appreciate the work you did, and I'll delve into it a bit more later today!

**Comment by kelseylondon** [comment]
I am closing this issue, because we have divided the tasks of creating roadmaps and updating the wiki into two separate issues: #727 and #774.
