### ISSUE TITLE
Create research roadmap for each target user group

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#727]
### Overview
The research team recently created a Research Roadmap that provides an overview of our goals, current research plans, and future research plans. In response to feedback from Bonnie, we will divide this document into _two_ roadmaps - one for each target user group. 

### Action Items

- [x] Create roadmap document for research with legal professionals
- [x] Create roadmap document for research with people personally involved with record clearing process

**Revising the Roadmap Documents (tasks for 11/18/2022)**
More detailed instructions for assigned tasks can be found on the relevant Google docs. 

_[Roadmap for Research with Legal Professionals](https://docs.google.com/document/d/1CmEbCae0v5L4nEuO3WqRE9KM8hOeewrfI6GJ7rfNg9Q/edit#heading=h.kmzkzb7ildci)_
- [x] Edit background section (can be same text for both roadmaps) - assigned to @kyle-whitaker 
- [x] Edit description of participants - assigned to @SamHyler 
- [x] Edit research framework section - assigned to ~~@jbsteinhardt~~ @kelseylondon (1/16/2023)
- [x] Revise content of research plan 1 (RP1) to align with content in Information Gathering survey research plan - assigned to ~~@nikitashah14~~ Kyle (not tagging, because he did this back in November - Kelsey, 1/16/2023)
- [x]  Change color of footer on p. 1 - assigned to @SamHyler 

_[Roadmap for Research with Justice-Impacted Individuals](https://docs.google.com/document/d/1iWBX6ueIoMoOkCzJe0RHKx3hnfY9AvS6FbbBGvgsQ4M/edit?usp=sharing)_
- [x] Edit background section (can be same text for both roadmaps) - assigned to @kyle-whitaker 
- [x] Edit description of participants - assigned to @SamHyler 
- [x] Edit research framework section - assigned to ~~@jbsteinhardt~~ @kelseylondon (1/16/2023)
- [x] Revise content of research plan 2 (RP2) to align with content in Terminology survey research plan - assigned to ~~Ayah~~ @kelseylondon (1/16/2023)
- [x] Revise content of research plan 4 (RP4) to reflect that research will be conducted with justice-impacted individuals - assigned to ~~Ayah~~ @kelseylondon (1/16/2023)
- [x] Change color of footer on p. 1 - assigned to @SamHyler 

_Note:_ we have been instructed not to include IUT1 and IUT2 in these roadmaps, because the participants for those research projects are HfLA volunteers. 

**Brainstorming (now scheduled for 1/20/2023)**
- #775 

**Next Steps**
- Edit notes and references for both roadmaps
- Write text for research goals and objectives for both roadmaps

### Relevant Issues

- #723 
- #775 

### Resources

- [Roadmap for Research with Legal Professionals (November 2022)](https://docs.google.com/document/d/1CmEbCae0v5L4nEuO3WqRE9KM8hOeewrfI6GJ7rfNg9Q/edit?usp=sharing)
- [Roadmap for Research with Justice-Impacted Individuals (November 2022)](https://docs.google.com/document/d/1iWBX6ueIoMoOkCzJe0RHKx3hnfY9AvS6FbbBGvgsQ4M/edit?usp=sharing)
- [Original Expunge Assist Research Roadmap (October 2022)](https://docs.google.com/document/d/1OJ0LD-oIICMz1kGsX6p7oYtPywYcWwvl6cmaW5gn6wc/edit)
- [Example Research Roadmap from Internship project](https://docs.google.com/document/d/1ywAYj0NMXQy53kVuEOmtVUdvGy51HqT67xak0EJrFXE/edit)

**Comment by SamHyler** [comment]
problem with the color change, not sure if it's possible or if I just don't know how. The only color change for the footer image I found had preset colors only, around 15 options, none of which was sufficiently close to EA's purple

**Comment by kelseylondon** [comment]
Just noting here that the footer on the first page of each roadmap has been changed - we did not create a new image but used the HfLA logo alongside the existing text.
