### ISSUE TITLE
Re-organizing and preparing Figma for IUT3

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#753]
### Overview
During the transitional phase between the end of designing for IUT2 and waiting for the results of testing, the Content and UX Design team need to prepare our Figma workspace for the next milestone. 

### Action Items
- [x] Design: Finish creating the mobile wireframes for Master pages (#641 )
- [x] Content: Review both desktop and mobile wireframes to ensure the correct copy exists on these pages https://github.com/hackforla/expunge-assist/issues/844
- [x] Content and Design will #807 
- [x] Content and Design team will move content from WIP to IUT2 page under archive
- [ ] Add content to the "Start here" page https://github.com/hackforla/expunge-assist/issues/773
- [ ] Add any other documentation to other pages
- [ ] Design and Content: Smooth out Design System (#750 )
- [ ] Design will clean and update the component library

**Comment by SamHyler** [comment]
@anitadesigns are we finished with this, or should we carve out a little time to finish it?

**Comment by anitadesigns** [comment]
Issues have been broken down for ongoing behind the scene work. Since we moved past IUT3, will close issue
