### ISSUE TITLE
Define research objectives for each user group

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#775]
### Overview
The research team recently created two roadmaps - one for each target user group - that provide an overview of our goals, current research plans, and future research plans. To complete these roadmaps, we need to identify our overarching research objectives for research with each user group. 

### Action Items

- [x] Create brainstorming Figjam
- [x] Use team meeting on 1/20/2023 to: 
    - [x] brainstorm what we want to learn from our key user groups
- [x] Use team meeting on 02/-3/2023 to:
    - [x] identify our main objectives for research with legal professionals
    - [x] identify our main objectives for research with justice-impacted individuals
    - [x] refine wording of our research objectives (to include in roadmaps)

### Next Steps
- Add research objectives to roadmap for research with legal professionals
- Add research objectives to roadmap for research with justice-impacted individuals
- Update wiki to include roadmaps

### Relevant Issues
- #723 
- #727 

### Resources
- [Brainstorming Figjam](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/2022-EoY-Reflection-and-Planning-Workshops?node-id=0%3A1&t=xM6ckgVC7UEJNe4K-1)
- [Roadmap for Research with Legal Professionals (November 2022)](https://docs.google.com/document/d/1CmEbCae0v5L4nEuO3WqRE9KM8hOeewrfI6GJ7rfNg9Q/edit?usp=sharing)
- [Roadmap for Research with Justice-Impacted Individuals (November 2022)](https://docs.google.com/document/d/1iWBX6ueIoMoOkCzJe0RHKx3hnfY9AvS6FbbBGvgsQ4M/edit?usp=sharing)

**Comment by kelseylondon** [comment]
Ran out of time during 1/20/2023 meeting to complete all tasks in this issue, so we'll revisit in meeting on 2/3/2023.

**Comment by yumengluo** [comment]
add research objectives to roadmap for research with legal professionals
 add research objectives to roadmap for research with justice-impacted individuals
those two tasks are completed.
