### ISSUE TITLE
Update Survey Outreach Tracker and archive Outreach-Partnerships database

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#850]
### Overview
We have received approval to carry out the Information Gathering and Terminology Surveys, originally developed in Summer/Fall 2022. As part of our preparation for disseminating these surveys, the outreach database and survey tracker must be updated, reviewed, and improved. 

### Action Items

- [x] Transfer relevant data from the [Outreach-Partnerships database](https://docs.google.com/spreadsheets/d/1hTOXq377vMAcacV07oRbzXEJdLqvnn9IV5xImHaIeEg/edit#gid=1803989007) to the [Survey Outreach Tracker](https://docs.google.com/spreadsheets/d/1u3IRialPEDEnDe186d7FvaP9mzzLbiZcISkfFjXX8rw/edit#gid=26489799)
- [x] Mark the [Outreach-Partnerships database](https://docs.google.com/spreadsheets/d/1hTOXq377vMAcacV07oRbzXEJdLqvnn9IV5xImHaIeEg/edit#gid=1803989007) as ARCHIVED
- [x] Notify research co-leads that the team can now review and improve on the [Survey Outreach Tracker](https://docs.google.com/spreadsheets/d/1u3IRialPEDEnDe186d7FvaP9mzzLbiZcISkfFjXX8rw/edit#gid=26489799)

### Resources/Instructions
- [Research Plan 1: Information Gathering Survey](https://docs.google.com/document/d/1HTzlBNJ304NfD9stoEhjfrrVg0KD2Qbm2gkVUJM7KUM/edit)
- [Instructions for Disseminating Information Gathering Survey](https://docs.google.com/document/d/1Vsd8QOTsFK9iNvZjFK0ymHvM653577_hvEAI84X0yXw/edit) - _note: needs to be revised_
- [Research Plan 2: Terminology Survey](https://docs.google.com/document/d/1advWUy3_QlYQlxY94ifTwaiEVNmdL5edCm87lYfK6cI/edit)
- [Instructions for Disseminating Terminology Survey](https://docs.google.com/document/d/1WOHNkJzBITELsmMlPY0Pokzt_afSyxvIcHsMeSfGkgA/edit) - _note: needs to be revised_

### Related issues
- #729
- #728  
- #714  
- #708  
- #669 
- #652 
- #603

**Comment by kelseylondon** [comment]
Apologies for the delay - this will be completed this evening.

**Comment by yumengluo** [comment]
Found another database in the Google drive: https://docs.google.com/spreadsheets/d/16tzlMCkiSJwGWihdQTCP9k3eYi_TevYFMo3_xYBgyjU/edit#gid=0

**Comment by kelseylondon** [comment]
@yumengluo - all that data is already in the existing database!

Also, I've updated [the tracker](https://docs.google.com/spreadsheets/d/1u3IRialPEDEnDe186d7FvaP9mzzLbiZcISkfFjXX8rw/edit#gid=1803665922), but we should discuss creating an issue to make sure the Legal Aid orgs list is up-to-date - many places on the list were last updated in 2021/early 2022.
