### ISSUE TITLE
Create Google Doc of Research Objectives Draft

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#851]
### Overview
We will need to identify our main objectives for research with legal professionals and with justice-impacted individuals. In order to do so, we had a brainstorming session on [FigJam](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?node-id=0%3A1&t=AqLKTySU32xT1SCi-0) on Jan 20 2023 and a follow-up session on Feb 10 2023. Issues were created for facilitating peer review of identified research objectives, but on Feb 17 2023, the team decided that review of the objectives would be better conducted via comments on a Google doc. 

### Action Items
- [x] Create Google doc of Research Objectives
   - [x] Include separate section for Research Objectives for Research with Legal Professionals
      - [x] Add sub-heading titled "Research Objectives"
      - [x] Add sub-heading titled "What do we want to learn?"
   - [x] Include separate section for Research Objectives for Research with Justice-Involved Individuals
      - [x] Add sub-heading titled "Research Objectives"
      - [x] Add sub-heading titled "What do we want to learn?"
- [x] Under the section Research Objectives for Research with Legal Professionals:
   - [x] Add list of research objectives under the sub-heading "Research Objectives"
   - [x] Add peer review feedback for each research objective as a comment on the Google doc
   - [x] Add list of brainstormed questions under the sub-heading "What do we want to learn"
- [x] Under the section Research Objectives for Research with Justice-Involved Individuals:
   - [x] Add list of research objectives under the sub-heading "Research Objectives"
   - [x] Add peer review feedback for each research objective as a comment on the Google doc
   - [x] Add list of brainstormed questions under the sub-heading "What do we want to learn"
- [x] Add document to the [Current Roadmaps Google Drive folder](https://drive.google.com/drive/folders/1qXMKszkE6VmmfTdnpcbuBsaQjwFPOY5R)
- [x] Create a new issue for the team to review/edit this document. 

### Resources/Instructions
- [FigJam](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?node-id=578%3A239&t=AqLKTySU32xT1SCi-0)
- [Current Roadmaps Google Drive folder](https://drive.google.com/drive/folders/1qXMKszkE6VmmfTdnpcbuBsaQjwFPOY5R)

### Relevant Issues
#775 
#800 
#799 
#798 
#797 
#796

**Comment by yumengluo** [comment]
Completed.
