### ISSUE TITLE
Define Requirements to Soft Launch EA Product

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#869]
### Overview
As a team, we would like to move forward with soft launching our product with potential target users. 

### Action Items
- [ ] Define MVP level product needed 
- [ ] Identify gap of existing product vs needed features
- [ ] Document and share with team for action
- [ ] 

### Resources/Instructions
Internal Usability Testing results will help inform any critical missing issues and feedback 
Short survey response feedback may also inform these requirements
Target users will potentially be sourced from short survey respondents (legal professionals/clinics or actual target users) 
Work with disciplines leads and PM's to prioritize remaining GH issues critically necessary to have soft launch. Deprioritize those items that are not
