### ISSUE TITLE
Create session tracker for IUT2

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#899]
### Overview
 As we are planning IUT2, we will need to create a session tracker to track all of the interview activities. 

### Action Items

- [x] Create a session. tracker
- [x] Put your availability on the Google sheet for user testing for date/time preferences
- [x] Put your preference for note-taking - Google Sheets or Docs
- [x] Link the session tracker to the research plan.
 
### Resources
 [research plan](https://docs.google.com/document/d/1TUHVwXvQBEeQc5t57RGdNmQUH_QVoZd1orBMeEloSOk/edit?pli=1#)

**Comment by yumengluo** [comment]
[Session tracker (https://docs.google.com/spreadsheets/d/1b2aEHmKtKFmWMBNw7t3cq1MYyXBUdPWfoxli0yci_8s/edit#gid=1931227377) was created.
