### ISSUE TITLE
Mission: Create framework for principles/attributes/? for discussion on Figjam

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#970]
### Overview
This issue is for Content and Design leads

High level: We have begun to start to define our Mission (statement), and to outline a brand guide in service of creating a roadmap for the next stages of EA's work. In this process, and from previous Content Guideline development, we have been looking at the 3 design principles that were on a design slide deck from pre June 2021 (and were used for the first iteration of the Content Guidelines). 

The idea is to find better keywords (attributes, design principles, or something else...we also need to choose which name we are using and why, and if these keywords will overlap between the mission and Content's work) that can guide our work, both at the high level like the mission, and in our Content Tone and Voice, and any corresponding Design work. 

### Action Items

- [x] Review exercises from UXW guides
- [x] Create exercises on Figjam board
- [x] Share with team at next meeting
- [ ] Process results and narrow down words
- [ ] Make a suggestion for keyword

### Resources/Instructions
Figjam board (add)

Content Voice and tone results at the bottom of this series in [FigJam](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=2348-6046&t=fbOKqCEb6bTFSxUX-4)  Connected to the Content Guideline work here https://github.com/hackforla/expunge-assist/issues/906

**Comment by SamHyler** [comment]
@anitadesigns @jyehllow @emmathrash Reviewing this one, ties into our brand book and the mission statement from last summer. Do you think we will proceed with the mission statement after the brand book or should we close? Will the brand book cover the mission statement?

**Comment by vanessaavviles** [comment]
@SamHyler @anitadesigns @jyehllow 
Please Provide an Update:

**Progress:**

**Estimation Time to Completion:** 

**Blockers:**

**Comment by SamHyler** [comment]
> @SamHyler @anitadesigns @jyehllow Please Provide an Update:
> 
> **Progress:**
> 
> **Estimation Time to Completion:**
> 
> **Blockers:**

As far as I know the blocker is the Brand book that was supposed to be done in spring. Not sure where that landed.

**Comment by anitadesigns** [comment]
That's correct @SamHyler ! Since Amanda was offboarded from the team, @vanessaavviles is creating an issue to recruit a new branding/marketing person

**Comment by SamHyler** [comment]
This would be a new feature, or stakeholder review 2.0. I believe the brand book is needed for stakeholder review, unsure which milestone to use but it isn't an existing feature.

**Comment by raeraeicky** [comment]
After PM discussion with Bonnie, confirmed that brand book is not required to go to partners, and it's also a much simpler resource that needs to be established. Closing this issue to start fresh.
